#!/bin/bash
# MIT License
#
# Copyright (c) 2022, N. Harris Computer Corporation
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

#####################################################################################
#                                                                                   #
#  Script to ingest data using the etl_client                                       #
#  db2_image for the DB2 server                                                     #
#                                                                                   #
#####################################################################################

# $1 - command to run
function runCommandUntilSuccess
{
    set +e

    eval $1
    while [ $? -ne 0 ]; do
        eval $1
    done

    set -e
}

echo "Ensure to source the db2profile"
. /home/db2inst1/sqllib/db2profile

echo "Load data"
runCommandUntilSuccess "db2 connect to ISTORE user i2analyze"

cd /opt/IBM/i2analyze/etltoolkit

#create an entity staging table
/opt/IBM/i2analyze/etltoolkit/createInformationStoreStagingTable -stid ET5 -sn IS_Staging -tn E_Person

#create a link staging table
/opt/IBM/i2analyze/etltoolkit/createInformationStoreStagingTable -stid LAS1 -sn IS_Staging -tn L_Associate

#populate the newly created E_Person staging table
db2 "import from /opt/IBM/i2analyze/example/person.csv of del modified by timestampformat=\"dd/mm/yyyy hh:mm:ss\" dateformat=\"dd/mm/yyyy\" method P(1,2,3,4,5,6) SKIPCOUNT 1 replace into IS_Staging.E_Person (SOURCE_ID,P_DATE_OF_BIRTH,P_FIRST_GIVEN_NAME,P_FAMILY_NAME,P_OCCUPATION,P_GENDER)"

#populate the newly created L_Associate staging table
db2 "import from /opt/IBM/i2analyze/example/person_association_person.csv of del modified by timestampformat=\"dd/mm/yyyy hh:mm:ss\" dateformat=\"dd/mm/yyyy\" method P(1,2,3,4,5) SKIPCOUNT 1  replace into IS_Staging.L_Associate (SOURCE_ID,FROM_SOURCE_ID,TO_SOURCE_ID,P_ASSOCIATION_TYPE,DIRECTION)"

#create the ingestion source
./addInformationStoreIngestionSource -n REMOTE -d "Remote ingestion source"

#ingest from the E_Person staging table to the InformationStore
./ingestInformationStoreRecords -imf /opt/IBM/i2analyze/example/mapping.xml -imid Person

#ingest from the L_Associate staging table to the InformationStore
./ingestInformationStoreRecords -imf /opt/IBM/i2analyze/example/mapping.xml -imid Associate

echo "Cleaning staging tables"
db2 TRUNCATE IS_Staging.E_Person IMMEDIATE;
db2 TRUNCATE IS_Staging.L_Associate IMMEDIATE;
