#!/bin/bash
# MIT License
#
# Copyright (c) 2022, N. Harris Computer Corporation
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

#####################################################################################
#                                                                                   #
#  Script to initialize the etl_client.                                             #
#                                                                                   #
#  Usage : initializeEtlClient enable/disable                                       #
#  The "security" argument will catalog the dbnode and ISTORE database.             #
#  using a secure port and SSL if set to enable. Defaults to disable.               #
#####################################################################################
function output
{
  echo ""
  echo "############################################################"
  echo "## $1"
  echo "############################################################"
}

security=${1:-disable}

echo "Ensure to source the db2profile"
. /home/db2inst1/sqllib/db2profile

db2 uncatalog db ISTORE &>/dev/null
db2 uncatalog node dbnode &>/dev/null

if [ $security = 'enable' ]; then
    output "Cataloguing the dbnode and ISTORE using the secure port and SSL"
    db2 catalog tcpip node dbnode remote db2 server 50001 security SSL
    db2 catalog database ISTORE at node dbnode
else
    output "Cataloguing the dbnode and ISTORE using the non secure port and TCPIP"
    db2 catalog tcpip node dbnode remote db2 server 50000
    db2 catalog database ISTORE at node dbnode
fi

echo "Providing the ETL toolkit with the location of the DB2 client"
sed -i 's/db.installation.dir=\/opt\/IBM\/db2/db.installation.dir=\/home\/db2inst1\/sqllib/g' /opt/IBM/i2analyze/etltoolkit/classes/Connection.properties
