#!/bin/bash
# i2, i2 Group, the i2 Group logo, and i2group.com are trademarks of N.Harris Computer Corporation.
# © N.Harris Computer Corporation (2022)
#
# SPDX short identifier: MIT

#####################################################################################
#                                                                                   #
#  Script to create convert a .jks key store to a .p12 key store using Java keytool.#
#                                                                                   #
#####################################################################################
. /opt/i2/utils/functions

#The value passed in when the script is called, this is the name of a container
uri=$1

#Set the variables for the specified container name
keystoreInputFile=/opt/i2/keys/stores/i2-${uri}-keystore.jks
keystoreOutputFile=/opt/i2/keys/stores/i2-${uri}-keystore.p12

#Convert the store to the PKCS12 format
runCommandUntilSuccess "/opt/i2/i2analyze/toolkit/tools/java/bin/keytool -importkeystore -srckeystore ${keystoreInputFile} -destkeystore ${keystoreOutputFile} -deststoretype PKCS12 -srcstorepass:env SSL_PASSWORD -deststorepass:env SSL_PASSWORD"
