#!/bin/bash
# MIT License
#
# Copyright (c) 2022, N. Harris Computer Corporation
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

#####################################################################################
#                                                                                   #
#  Script to create convert a .jks key store to a .p12 key store using Java keytool.#
#                                                                                   #
#####################################################################################
. /opt/IBM/utils/functions

#The value passed in when the script is called, this is the name of a container
uri=$1

#Set the variables for the specified container name
keystoreInputFile=/opt/IBM/keys/stores/i2-${uri}-keystore.jks
keystoreOutputFile=/opt/IBM/keys/stores/i2-${uri}-keystore.p12

#Convert the store to the PKCS12 format
runCommandUntilSuccess "/opt/IBM/i2analyze/toolkit/tools/java/bin/keytool -importkeystore -srckeystore ${keystoreInputFile} -destkeystore ${keystoreOutputFile} -deststoretype PKCS12 -srcstorepass:env SSL_PASSWORD -deststorepass:env SSL_PASSWORD"
