#!/bin/bash
#/********************************************************************************
# * (C) Copyright IBM Corporation 2018, 2020.
# *
# * This program and the accompanying materials are made available under the
# * terms of the Eclipse Public License 2.0 which is available at
# * http://www.eclipse.org/legal/epl-2.0.
# *
# * SPDX-License-Identifier: EPL-2.0
# *
# ********************************************************************************/

#####################################################################################
#                                                                                   #
#  Script to create convert a .jks key store to a .p12 key store using Java keytool.#
#                                                                                   #
#####################################################################################
. /opt/IBM/utils/functions

#The value passed in when the script is called, this is the name of a container
uri=$1

#Set the variables for the specified container name
keystoreInputFile=/opt/IBM/keys/stores/i2-${uri}-keystore.jks
keystoreOutputFile=/opt/IBM/keys/stores/i2-${uri}-keystore.p12

#Convert the store to the PKCS12 format
runCommandUntilSuccess "/opt/IBM/i2analyze/toolkit/tools/java/bin/keytool -importkeystore -srckeystore ${keystoreInputFile} -destkeystore ${keystoreOutputFile} -deststoretype PKCS12"
