#!/bin/bash
# MIT License
#
# Copyright (c) 2022, N. Harris Computer Corporation
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

#####################################################################################
#                                                                                   #
#  Script to create a certificate signing request using Java keytool.               #
#                                                                                   #
#####################################################################################
. /opt/IBM/utils/functions

#The value passed in when the script is called, this is the name of a container.
#If optional second parameter is passed in, the second parameter will be used as the keyStoreId.
#If optional third parameter is passed in, the third parameter will be used as the CN value.
uri=$1
keyStoreId=${2:-$1}
commonName=${3:-${1}.eianet}

#Set the variables for the specified container name
keystoreFile=/opt/IBM/keys/stores/i2-${keyStoreId}-keystore.jks
keyName=${uri}key
out=/opt/IBM/keys/requests/${uri}-key.csr

#Create the requests directory
mkdir -p /opt/IBM/keys/requests

#Create the stores directory
mkdir -p /opt/IBM/keys/stores

#Generate new certificate pair for the container, where the CN matches the host name of the container
runCommandUntilSuccess "/opt/IBM/i2analyze/toolkit/tools/java/bin/keytool -genkeypair -alias $keyName -keystore $keystoreFile -dname CN=$commonName -keyalg RSA -keypass:env SSL_PASSWORD -storepass:env SSL_PASSWORD"

#Create certificate signing request for the public certificate
runCommandUntilSuccess "/opt/IBM/i2analyze/toolkit/tools/java/bin/keytool -certreq -keystore $keystoreFile -alias $keyName -keyalg RSA -keysize 2048 -file $out -storepass:env SSL_PASSWORD"

#Change ownership to make visible to keys group
chown -R root:keys /opt/IBM/keys
chmod -R 650 /opt/IBM/keys
