#!/bin/bash
# i2, i2 Group, the i2 Group logo, and i2group.com are trademarks of N.Harris Computer Corporation.
# © N.Harris Computer Corporation (2022-2023)
#
# SPDX short identifier: MIT

#####################################################################################
#                                                                                   #
#  Script to set up the key stores used for SSL.                                    #
#                                                                                   #
#####################################################################################
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/ibm/gsk8_64/lib64
cd /opt/i2/i2analyze/deploy/keys/stores
/usr/local/ibm/gsk8_64/bin/gsk8capicmd_64 -keydb -stashpw -db /opt/i2/i2analyze/deploy/keys/stores/i2-db2-truststore.kdb
