#!/bin/bash
# i2, i2 Group, the i2 Group logo, and i2group.com are trademarks of N.Harris Computer Corporation.
# © N.Harris Computer Corporation (2022-2023)
#
# SPDX short identifier: MIT

#####################################################################################
#                                                                                   #
#  Script to copy default configuration into image folders for building images.     #
#                                                                                   #
#  Usage : copyConfiguration [<dbDialect>]                                          #
#  Defaults to current database dialect                                             #
#                                                                                   #
#####################################################################################

set -e

. utils/variables

pushd ..

. ${UTILS_PATH}/functions

dbDialect=${1:-${DB_DIALECT}}

if [[ $dbDialect != "sqlserver" &&  $dbDialect != "db2" &&  $dbDialect != "postgres" ]]; then
    echo "Error: Unrecognized dialect."
    exit 1
fi

output "Cleaning the user configuration"
#Common contexts
rm -rf "${IMAGES_PATH}/common/zookeeper/configuration" &>/dev/null || true
rm -rf "${IMAGES_PATH}/common/zookeeper2/configuration" &>/dev/null || true
rm -rf "${IMAGES_PATH}/common/zookeeper3/configuration" &>/dev/null || true
rm -rf "${IMAGES_PATH}/common/solr/configuration" &>/dev/null || true
rm -rf "${IMAGES_PATH}/common/solr2/configuration" &>/dev/null || true
rm -rf "${IMAGES_PATH}/common/ihs/configuration" &>/dev/null || true

#Dialect specific
rm -rf "${IMAGES_PATH}/${dbDialect}/liberty/configuration" &>/dev/null || true
rm -rf "${IMAGES_PATH}/${dbDialect}/admin_client/configuration" &>/dev/null || true

output "Copying the user configuration into all of the required Docker contexts"
#Common contexts
cp -r "${DEFAULT_CONFIG_PATH}" "${IMAGES_PATH}/common/zookeeper/configuration"
cp -r "${DEFAULT_CONFIG_PATH}" "${IMAGES_PATH}/common/zookeeper2/configuration"
cp -r "${DEFAULT_CONFIG_PATH}" "${IMAGES_PATH}/common/zookeeper3/configuration"
cp -r "${DEFAULT_CONFIG_PATH}" "${IMAGES_PATH}/common/solr/configuration"
cp -r "${DEFAULT_CONFIG_PATH}" "${IMAGES_PATH}/common/solr2/configuration"
cp -r "${DEFAULT_CONFIG_PATH}" "${IMAGES_PATH}/common/ihs/configuration"

#Dialect specific
cp -r "${DEFAULT_CONFIG_PATH}" "${IMAGES_PATH}/${dbDialect}/liberty/configuration"
cp -r "${DEFAULT_CONFIG_PATH}" "${IMAGES_PATH}/${dbDialect}/admin_client/configuration"

popd
