#!/bin/bash
# i2, i2 Group, the i2 Group logo, and i2group.com are trademarks of N.Harris Computer Corporation.
# © N.Harris Computer Corporation (2022)
#
# SPDX short identifier: MIT

#####################################################################################
#                                                                                   #
#  Script to back up the current configuration of the admin_client container.       #
#  This scripts assumes the admin_client contains the complete configuration        #
#  for the deployment.                                                              #
#                                                                                   #
#  Usage : backupConfiguration                                                      #
#                                                                                   #
#####################################################################################

set -e

. utils/variables

pushd ..

. ${UTILS_PATH}/functions

rm -rf ${CONFIG_MODS_PATH}/configuration_backup &>/dev/null || true

output "Backing up the configuration from the admin_client container."
docker cp admin_client:/opt/i2/i2analyze/toolkit/configuration ${CONFIG_MODS_PATH}/configuration_backup

popd
