#!/bin/bash
# MIT License
#
# Copyright (c) 2022, N. Harris Computer Corporation
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

#####################################################################################
#                                                                                   #
#  Script to remove all the containers, images, and networks.                       #
#  Additionally, it returns to the default configuration in all folders.            #
#                                                                                   #
#  Usage : clean                                                                    #
#                                                                                   #
#####################################################################################

. utils/variables

pushd ..

. "${UTILS_PATH}"/functions

output "Cleaning up any previous created containers, images, and networks"
docker rm -f zookeeper zookeeper2 zookeeper3 solr solr2 db2 sqlserver liberty admin_client etl_client ihs ca solr3 connector &>/dev/null || true
docker rmi -f zookeeper_image zookeeper2_image zookeeper3_image solr_image solr2_image base_ihs_image ihs_image ca_image connector_image &>/dev/null || true
docker rmi -f liberty_sqlserver_image liberty_db2_image etl_client_sqlserver_image etl_client_db2_image &>/dev/null || true
docker rmi -f sqlserver_image db2_installer_image db2_image admin_client_sqlserver_image admin_client_db2_image base_client_image &>/dev/null || true
docker rmi -f ubuntu_toolkit_image &>/dev/null || true
docker network rm eianet &>/dev/null || true

output "Cleaning up the copied user configuration"
rm -rf ${IMAGES_PATH}/common/zookeeper/configuration &>/dev/null || true
rm -rf ${IMAGES_PATH}/common/zookeeper2/configuration &>/dev/null || true
rm -rf ${IMAGES_PATH}/common/zookeeper3/configuration &>/dev/null || true
rm -rf ${IMAGES_PATH}/common/solr/configuration &>/dev/null || true
rm -rf ${IMAGES_PATH}/common/solr2/configuration &>/dev/null || true
rm -rf ${IMAGES_PATH}/common/ihs/configuration &>/dev/null || true
rm -rf ${IMAGES_PATH}/common/solr3/configuration &>/dev/null || true
rm -rf ${IMAGES_PATH}/db2/liberty/configuration &>/dev/null || true
rm -rf ${IMAGES_PATH}/db2/admin_client/configuration &>/dev/null || true
rm -rf ${IMAGES_PATH}/sqlserver/liberty/configuration &>/dev/null || true
rm -rf ${IMAGES_PATH}/sqlserver/admin_client/configuration &>/dev/null || true

output "Cleaning up keys"
rm -r ${SRC_DIR}/keys &>/dev/null || true

popd
