#!/bin/bash
#/********************************************************************************
# * (C) Copyright IBM Corporation 2018, 2019.
# *
# * This program and the accompanying materials are made available under the
# * terms of the Eclipse Public License 2.0 which is available at
# * http://www.eclipse.org/legal/epl-2.0.
# *
# * SPDX-License-Identifier: EPL-2.0
# *
# ********************************************************************************/

#####################################################################################
#                                                                                   #
#  Script to remove all the containers, images and networks plus clean up           #
#  the configuration in all folders                                                 #
#                                                                                   #
#  Usage : clean                                                                    #
#                                                                                   #
#####################################################################################

. utils/variables

pushd ..

. ${UTILS_PATH}/functions

output "Cleaning up any previous created containers, images, and networks"
docker rm -f zookeeper solr solr2 db2 liberty admin_client etl_client ihs ca zookeeper2 zookeeper3 solr3 connector &>/dev/null || true
docker rmi -f zookeeper_image solr_image solr2_image ihs_image liberty_image etl_client_image ca_image connector_image &>/dev/null || true
docker rmi -f db2_installer_image db2_image admin_client_image base_client_image &>/dev/null || true
docker rmi -f ubuntu_toolkit_image &>/dev/null || true
docker network rm eianet &>/dev/null || true

output "Cleaning up the copied user configuration"
rm -rf ${IMAGES_PATH}/liberty/configuration &>/dev/null || true
rm -rf ${IMAGES_PATH}/zookeeper/configuration &>/dev/null || true
rm -rf ${IMAGES_PATH}/solr/configuration &>/dev/null || true
rm -rf ${IMAGES_PATH}/solr2/configuration &>/dev/null || true
rm -rf ${IMAGES_PATH}/admin_client/configuration &>/dev/null || true
rm -rf ${IMAGES_PATH}/ihs/configuration &>/dev/null || true
rm -rf ${IMAGES_PATH}/zookeeper2/configuration &>/dev/null || true
rm -rf ${IMAGES_PATH}/zookeeper3/configuration &>/dev/null || true
rm -rf ${IMAGES_PATH}/solr3/configuration &>/dev/null || true

output "Cleaning up keys"
rm -r ${SRC_DIR}/keys &>/dev/null || true

popd
