#!/bin/bash
#/********************************************************************************
# * (C) Copyright IBM Corporation 2018, 2019.
# *
# * This program and the accompanying materials are made available under the
# * terms of the Eclipse Public License 2.0 which is available at
# * http://www.eclipse.org/legal/epl-2.0.
# *
# * SPDX-License-Identifier: EPL-2.0
# *
# ********************************************************************************/

#####################################################################################
#                                                                                   #
#  Script to copy default configuration into image folders for building images.     #
#                                                                                   #
#  Usage : copyConfiguration                                                        #
#                                                                                   #
#####################################################################################

set -e

. utils/variables

pushd ..

. ${UTILS_PATH}/functions

output "Cleaning the user configuration"
rm -rf ${IMAGES_PATH}/liberty/configuration &>/dev/null || true
rm -rf ${IMAGES_PATH}/zookeeper/configuration &>/dev/null || true
rm -rf ${IMAGES_PATH}/solr/configuration &>/dev/null || true
rm -rf ${IMAGES_PATH}/solr2/configuration &>/dev/null || true
rm -rf ${IMAGES_PATH}/admin_client/configuration &>/dev/null || true
rm -rf ${IMAGES_PATH}/ihs/configuration &>/dev/null || true

output "Copying the user configuration into all of the required Docker contexts"
cp -r ${DEFAULT_CONFIG_PATH} ${IMAGES_PATH}/liberty/configuration
cp -r ${DEFAULT_CONFIG_PATH} ${IMAGES_PATH}/zookeeper/configuration
cp -r ${DEFAULT_CONFIG_PATH} ${IMAGES_PATH}/solr/configuration
cp -r ${DEFAULT_CONFIG_PATH} ${IMAGES_PATH}/solr2/configuration
cp -r ${DEFAULT_CONFIG_PATH} ${IMAGES_PATH}/admin_client/configuration
cp -r ${DEFAULT_CONFIG_PATH} ${IMAGES_PATH}/ihs/configuration

popd
