#!/bin/bash
#/********************************************************************************
# * (C) Copyright IBM Corporation 2018, 2019.
# *
# * This program and the accompanying materials are made available under the
# * terms of the Eclipse Public License 2.0 which is available at
# * http://www.eclipse.org/legal/epl-2.0.
# *
# * SPDX-License-Identifier: EPL-2.0
# *
# ********************************************************************************/

#####################################################################################
#                                                                                   #
#  Script to copy default configuration into image folders for building images.     #
#                                                                                   #
#  Usage : copyConfiguration [<dbDialect>]                                          #
#  Defaults to current dialect                                                      #
#                                                                                   #
#####################################################################################

set -e

. utils/variables

pushd ..

. ${UTILS_PATH}/functions

dbDialect=${1:-${DB_DIALECT}}

if [[ $dbDialect != "sqlserver" &&  $dbDialect != "db2" ]]; then
    echo "Error: Unrecognized dialect."
    exit 1
fi

output "Cleaning the user configuration"
#Common contexts
rm -rf "${IMAGES_PATH}/common/zookeeper/configuration" &>/dev/null || true
rm -rf "${IMAGES_PATH}/common/solr/configuration" &>/dev/null || true
rm -rf "${IMAGES_PATH}/common/solr2/configuration" &>/dev/null || true
rm -rf "${IMAGES_PATH}/common/ihs/configuration" &>/dev/null || true

if [[ $dbDialect == "db2" ]]; then
    #DB2 contexts
    rm -rf "${IMAGES_PATH}/db2/liberty/configuration" &>/dev/null || true
    rm -rf "${IMAGES_PATH}/db2/admin_client/configuration" &>/dev/null || true
fi
if [[ $dbDialect == "sqlserver" ]]; then
    #Microsoft SQL contexts
    rm -rf "${IMAGES_PATH}/sqlserver/liberty/configuration" &>/dev/null || true
    rm -rf "${IMAGES_PATH}/sqlserver/admin_client/configuration" &>/dev/null || true
fi

output "Copying the user configuration into all of the required Docker contexts"
#Common contexts
cp -r "${DEFAULT_CONFIG_PATH}" "${IMAGES_PATH}/common/zookeeper/configuration"
cp -r "${DEFAULT_CONFIG_PATH}" "${IMAGES_PATH}/common/solr/configuration"
cp -r "${DEFAULT_CONFIG_PATH}" "${IMAGES_PATH}/common/solr2/configuration"
cp -r "${DEFAULT_CONFIG_PATH}" "${IMAGES_PATH}/common/ihs/configuration"

#Dialect specific
cp -r "${DEFAULT_CONFIG_PATH}" "${IMAGES_PATH}/${dbDialect}/liberty/configuration"
cp -r "${DEFAULT_CONFIG_PATH}" "${IMAGES_PATH}/${dbDialect}/admin_client/configuration"

popd
