#!/bin/bash
# MIT License
#
# Copyright (c) 2022, N. Harris Computer Corporation
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

#####################################################################################
#                                                                                   #
#  Script to copy default configuration into image folders for building images.     #
#                                                                                   #
#  Usage : copyConfiguration [<dbDialect>]                                          #
#  Defaults to current database dialect                                             #
#                                                                                   #
#####################################################################################

set -e

. utils/variables

pushd ..

. ${UTILS_PATH}/functions

dbDialect=${1:-${DB_DIALECT}}

if [[ $dbDialect != "sqlserver" &&  $dbDialect != "db2" ]]; then
    echo "Error: Unrecognized dialect."
    exit 1
fi

output "Cleaning the user configuration"
#Common contexts
rm -rf "${IMAGES_PATH}/common/zookeeper/configuration" &>/dev/null || true
rm -rf "${IMAGES_PATH}/common/zookeeper2/configuration" &>/dev/null || true
rm -rf "${IMAGES_PATH}/common/zookeeper3/configuration" &>/dev/null || true
rm -rf "${IMAGES_PATH}/common/solr/configuration" &>/dev/null || true
rm -rf "${IMAGES_PATH}/common/solr2/configuration" &>/dev/null || true
rm -rf "${IMAGES_PATH}/common/ihs/configuration" &>/dev/null || true

if [[ $dbDialect == "db2" ]]; then
    #DB2 contexts
    rm -rf "${IMAGES_PATH}/db2/liberty/configuration" &>/dev/null || true
    rm -rf "${IMAGES_PATH}/db2/admin_client/configuration" &>/dev/null || true
fi
if [[ $dbDialect == "sqlserver" ]]; then
    #Microsoft SQL contexts
    rm -rf "${IMAGES_PATH}/sqlserver/liberty/configuration" &>/dev/null || true
    rm -rf "${IMAGES_PATH}/sqlserver/admin_client/configuration" &>/dev/null || true
fi

output "Copying the user configuration into all of the required Docker contexts"
#Common contexts
cp -r "${DEFAULT_CONFIG_PATH}" "${IMAGES_PATH}/common/zookeeper/configuration"
cp -r "${DEFAULT_CONFIG_PATH}" "${IMAGES_PATH}/common/zookeeper2/configuration"
cp -r "${DEFAULT_CONFIG_PATH}" "${IMAGES_PATH}/common/zookeeper3/configuration"
cp -r "${DEFAULT_CONFIG_PATH}" "${IMAGES_PATH}/common/solr/configuration"
cp -r "${DEFAULT_CONFIG_PATH}" "${IMAGES_PATH}/common/solr2/configuration"
cp -r "${DEFAULT_CONFIG_PATH}" "${IMAGES_PATH}/common/ihs/configuration"

#Dialect specific
cp -r "${DEFAULT_CONFIG_PATH}" "${IMAGES_PATH}/${dbDialect}/liberty/configuration"
cp -r "${DEFAULT_CONFIG_PATH}" "${IMAGES_PATH}/${dbDialect}/admin_client/configuration"

popd
