#!/bin/bash
#/********************************************************************************
# * (C) Copyright IBM Corporation 2018, 2020.
# *
# * This program and the accompanying materials are made available under the
# * terms of the Eclipse Public License 2.0 which is available at
# * http://www.eclipse.org/legal/epl-2.0.
# *
# * SPDX-License-Identifier: EPL-2.0
# *
# ********************************************************************************/

#####################################################################################
#                                                                                   #
#  Script to create the stores, private keys, and certificates for a                #
#  secure deployment. The stores are populated with signed certificate.             #
#                                                                                   #
#  Usage : createKeysAndStores [<dbDialect>]                                        #
#  Defaults to current database dialect                                             #
#                                                                                   #
#####################################################################################

. utils/variables

pushd ..

. ${UTILS_PATH}/functions

dbDialect=${1:-${DB_DIALECT}}

output "Removing the certificate authority container, if it exists"
docker rm -f ca &>/dev/null || true

output "Removing any previous keys, if they exist"
rm -rf ${SRC_DIR}/keys &>/dev/null || true

output "Building the ca_image"
docker build -t ca_image ${IMAGES_PATH}/common/ca

output "Running the certificate authority container"
docker run -d --name ca ca_image

header "Creating and signing the keys and certificates"
. ${SSL_SCRIPTS_PATH}/createSigningRequests $dbDialect
. ${SSL_SCRIPTS_PATH}/signRequests $dbDialect
. ${SSL_SCRIPTS_PATH}/applyResponses $dbDialect

popd
