#!/bin/bash
#/********************************************************************************
# * (C) Copyright IBM Corporation 2018, 2019.
# *
# * This program and the accompanying materials are made available under the
# * terms of the Eclipse Public License 2.0 which is available at
# * http://www.eclipse.org/legal/epl-2.0.
# *
# * SPDX-License-Identifier: EPL-2.0
# *
# ********************************************************************************/

#####################################################################################
#                                                                                   #
#  Script to switch from Db2 deployment to Sql Server deployment.                   #
#                                                                                   #
#  Usage : deploySqlServer                                                          #
#                                                                                   #
#####################################################################################

set -e

. utils/variables

pushd ..

. ${UTILS_PATH}/functions

#Update the base configuration with SQL Server
cp -r "${CONFIG_MODS_PATH}/sqlserver/base/." "${DEFAULT_CONFIG_PATH}"

pushd ${SCRIPTS_PATH}
. copyConfiguration sqlserver
popd

output "Copy the configuration to each container"
#Copy Modifications
docker cp "${IMAGES_PATH}/common/zookeeper/configuration/." zookeeper:/opt/IBM/i2analyze/toolkit/configuration
docker cp "${IMAGES_PATH}/common/solr/configuration/." solr:/opt/IBM/i2analyze/toolkit/configuration
docker cp "${IMAGES_PATH}/common/solr2/configuration/." solr2:/opt/IBM/i2analyze/toolkit/configuration

#Change the ownership of the copied files
docker exec -u root zookeeper chown -R i2analyze:i2analyze /opt/IBM/i2analyze/toolkit/configuration
docker exec -u root solr chown -R i2analyze:i2analyze /opt/IBM/i2analyze/toolkit/configuration
docker exec -u root solr2 chown -R i2analyze:i2analyze /opt/IBM/i2analyze/toolkit/configuration

# If the HTTP Server container exists then reset the configuration
contExists="$(containerExists ihs)"
if [[ "$contExists" -eq 1 ]]; then
    docker cp "${IMAGES_PATH}/common/ihs/configuration/." ihs:/opt/IBM/i2analyze/toolkit/configuration
    docker exec -u root ihs chown -R i2analyze:i2analyze /opt/IBM/i2analyze/toolkit/configuration
fi

output "Building liberty_image"
docker build -t liberty_sqlserver_image ${IMAGES_PATH}/sqlserver/liberty

output "Building admin_client_image"
docker build -t admin_client_sqlserver_image ${IMAGES_PATH}/sqlserver/admin_client

output "Building etl_client_image"
docker build -t etl_client_sqlserver_image ${IMAGES_PATH}/sqlserver/etl_client

output "Cleaning up any previously created deployment example containers if they exist."
docker stop db2 &>/dev/null || true
docker rm -f sqlserver admin_client liberty etl_client &>/dev/null || true

output "Running the sqlserver container on the eia network."
echo -n "Enter a password for the SA account: "
read -s saPassword
docker run -d -e 'ACCEPT_EULA=Y' -e "SA_PASSWORD=${saPassword}" --name sqlserver -p 1433:1433 --net eianet sqlserver_image

output "Waiting to ensure that the Microsoft SQL Server is running"
waitForContainer sqlserver "Service Broker manager has started"

output "Enter the password that you specified for db.infostore.password in the credentials.properties file:"
read -s password
docker exec -t sqlserver /opt/mssql-tools/bin/sqlcmd -U SA -P ${saPassword} -Q "CREATE LOGIN i2analyze WITH PASSWORD = '${password}'; CREATE USER i2analyze FOR LOGIN i2analyze; ALTER SERVER ROLE sysadmin ADD MEMBER i2analyze"

output "Running the admin client container on the eia network."
docker run -d --name admin_client --net eianet -u i2analyze admin_client_sqlserver_image
waitForContainer admin_client 'Started'

output "Running the admin_client container to create the database"
docker exec -t -u i2analyze admin_client /opt/IBM/i2analyze/toolkit/scripts/setup -t createDatabases

output "Restarting ZooKeeper"
docker exec -u i2analyze zookeeper /opt/IBM/i2analyze/toolkit/scripts/setup -t restartZkHosts --hostname zookeeper

output "Updating the Solr configuration on the ZooKeeper server"
docker exec -u i2analyze zookeeper /opt/IBM/i2analyze/toolkit/scripts/setup -t createAndUploadSolrConfig --hostname admin_client

output "Restarting Solr"
docker exec -u i2analyze -t solr /opt/IBM/i2analyze/toolkit/scripts/setup -t restartSolrNodes --hostname solr

docker exec -u i2analyze -t solr2 /opt/IBM/i2analyze/toolkit/scripts/setup -t restartSolrNodes --hostname solr2

output "Clear old search index"
docker exec -t -u i2analyze admin_client /opt/IBM/i2analyze/toolkit/scripts/setup -t clearSearchIndex --all --force --hostname admin_client

output "Running the liberty container on the eia network"
docker run -d --name liberty -p 9082:9082 -p 9445:9445 --net eianet -u i2analyze liberty_sqlserver_image

waitForContainer liberty 'Application started'

output "Running the etl client on the eia network"
docker run -d --name etl_client --net eianet -u i2analyze etl_client_sqlserver_image

popd
