#!/bin/bash
# i2, i2 Group, the i2 Group logo, and i2group.com are trademarks of N.Harris Computer Corporation.
# © N.Harris Computer Corporation (2022)
#
# SPDX short identifier: MIT

#####################################################################################
#                                                                                   #
#  Script to switch from Sql Server deployment to Postgres deployment.              #
#                                                                                   #
#  Usage : deployPostgres                                                           #
#                                                                                   #
#####################################################################################

set -e

. utils/variables

pushd ..

. ${UTILS_PATH}/functions

#Update the base configuration with Postgres
cp -r "${CONFIG_MODS_PATH}/postgres/base/." "${DEFAULT_CONFIG_PATH}"

pushd ${SCRIPTS_PATH}
. copyConfiguration postgres
popd

output "Copy the configuration to each container"
#Copy modifications
docker cp "${IMAGES_PATH}/common/zookeeper/configuration/." zookeeper:/opt/i2/i2analyze/toolkit/configuration
docker cp "${IMAGES_PATH}/common/zookeeper2/configuration/." zookeeper2:/opt/i2/i2analyze/toolkit/configuration
docker cp "${IMAGES_PATH}/common/zookeeper3/configuration/." zookeeper3:/opt/i2/i2analyze/toolkit/configuration
docker cp "${IMAGES_PATH}/common/solr/configuration/." solr:/opt/i2/i2analyze/toolkit/configuration
docker cp "${IMAGES_PATH}/common/solr2/configuration/." solr2:/opt/i2/i2analyze/toolkit/configuration

#Change the ownership of the copied files
docker exec -u root zookeeper chown -R i2analyze:i2analyze /opt/i2/i2analyze/toolkit/configuration
docker exec -u root zookeeper2 chown -R i2analyze:i2analyze /opt/i2/i2analyze/toolkit/configuration
docker exec -u root zookeeper3 chown -R i2analyze:i2analyze /opt/i2/i2analyze/toolkit/configuration
docker exec -u root solr chown -R i2analyze:i2analyze /opt/i2/i2analyze/toolkit/configuration
docker exec -u root solr2 chown -R i2analyze:i2analyze /opt/i2/i2analyze/toolkit/configuration

# If the HTTP Server container exists then reset the configuration
contExists="$(containerExists ihs)"
if [[ "$contExists" -eq 1 ]]; then
    docker cp "${IMAGES_PATH}/common/ihs/configuration/." ihs:/opt/i2/i2analyze/toolkit/configuration
    docker exec -u root ihs chown -R i2analyze:i2analyze /opt/i2/i2analyze/toolkit/configuration
fi

output "Building postgres_image"
docker build -t postgres_image ${IMAGES_PATH}/postgres/postgres

output "Building liberty_image"
docker build -t liberty_postgres_image ${IMAGES_PATH}/postgres/liberty
output "Building admin_client_image"
docker build -t admin_client_postgres_image ${IMAGES_PATH}/postgres/admin_client

output "Building etl_client_image"
docker build -t etl_client_postgres_image ${IMAGES_PATH}/postgres/etl_client

output "Cleaning up any previously created deployment example containers if they exist."
docker stop sqlserver &>/dev/null || true
docker stop db2 &>/dev/null || true
docker rm -f postgres admin_client liberty etl_client &>/dev/null || true

output "Enter the password that you specified for db.infostore.password in the credentials.properties file:"
read -s postgres_password
output "Running the postgres container on the eia network."
docker run -d -e 'POSTGRES_USER=i2analyze' -e "POSTGRES_PASSWORD=${postgres_password}" --name postgres -p 5432:5432 --net eianet postgres_image

output "Waiting to ensure that the postgres server is running"
waitForContainer postgres "database system is ready to accept connections"

output "Running the admin client container on the eia network."
docker run -d --name admin_client --net eianet --memory=1g -u i2analyze admin_client_postgres_image
waitForContainer admin_client 'Started'

output "Running the admin_client container to create the database"
docker exec -t -u i2analyze admin_client bash -c "/opt/i2/i2analyze/toolkit/scripts/setup -t createDatabases"

output "Restarting ZooKeeper"
docker restart zookeeper
docker restart zookeeper2
docker restart zookeeper3

output "Updating the Solr configuration on the ZooKeeper servers"
docker exec -u i2analyze admin_client /opt/i2/i2analyze/toolkit/scripts/setup -t createAndUploadSolrConfig --hostname admin_client.eianet

output "Restarting Solr"
docker exec -u i2analyze -t solr /opt/i2/i2analyze/toolkit/scripts/setup -t restartSolrNodes --hostname solr.eianet

docker exec -u i2analyze -t solr2 /opt/i2/i2analyze/toolkit/scripts/setup -t restartSolrNodes --hostname solr2.eianet

output "Clear old search index"
docker exec -t -u i2analyze admin_client /opt/i2/i2analyze/toolkit/scripts/setup -t clearSearchIndex --all --force --hostname admin_client.eianet

output "Running the liberty container on the eia network"
docker run -d --name liberty --memory=2g -p 9082:9082 -p 9445:9445 --net eianet -u i2analyze liberty_postgres_image

waitForContainer liberty 'Application started'

output "Running the etl client on the eia network"
docker run -d --name etl_client --memory=512m --net eianet -u i2analyze etl_client_postgres_image

popd
