#!/bin/bash
#/********************************************************************************
# * (C) Copyright IBM Corporation 2018, 2019.
# *
# * This program and the accompanying materials are made available under the
# * terms of the Eclipse Public License 2.0 which is available at
# * http://www.eclipse.org/legal/epl-2.0.
# *
# * SPDX-License-Identifier: EPL-2.0
# *
# ********************************************************************************/

#####################################################################################
#                                                                                   #
#  Script to set up the etl_client for use and to ingest example data               #
#                                                                                   #
#  Usage : deployEtlClient                                                          #
#                                                                                   #
#####################################################################################

set -e

. utils/variables

pushd ..

. ${UTILS_PATH}/functions

output "Removing old etltoolkit from etl_client and admin_client if exists"
docker exec -u i2analyze etl_client rm -Rf /opt/IBM/i2analyze/etltoolkit
docker exec -u i2analyze admin_client rm -Rf /opt/IBM/i2analyze/etltoolkit

output "Creating an etltoolkit and moving it to the etl_client container"
docker exec -u i2analyze admin_client /opt/IBM/i2analyze/toolkit/scripts/setup -t createEtlToolkit -p outputPath='/opt/IBM/i2analyze'

rm -rf etltoolkit &>/dev/null || true
docker cp admin_client:/opt/IBM/i2analyze/etltoolkit ./
docker exec -u i2analyze admin_client rm -R /opt/IBM/i2analyze/etltoolkit

docker cp ./etltoolkit etl_client:/opt/IBM/i2analyze/etltoolkit
rm -rf etltoolkit &>/dev/null || true
docker exec -u root -it etl_client chown -R i2analyze:db2iusr1 /opt/IBM/i2analyze/

popd
