#!/bin/bash
#/********************************************************************************
# * (C) Copyright IBM Corporation 2018, 2020.
# *
# * This program and the accompanying materials are made available under the
# * terms of the Eclipse Public License 2.0 which is available at
# * http://www.eclipse.org/legal/epl-2.0.
# *
# * SPDX-License-Identifier: EPL-2.0
# *
# ********************************************************************************/

#####################################################################################
#                                                                                   #
#  Script to remove the previous version of the toolkit and installs the new        #
#  toolkit. This scripts assumes the original configuration has been backed up,     #
#  as it overrides any files in the configuration folder.                           #
#                                                                                   #
#  Usage : installToolkit <toolkitPath>                                             #
#                                                                                   #
#####################################################################################

set -e

. utils/variables

pushd ..

. ${UTILS_PATH}/functions

echo "Are you sure you want to install a new toolkit? This removes your current installation. Make sure to backup your configuration before you continue."
while true; do
    read -p "Continue Y/N?" yn
    case $yn in
        [Yy]* ) break;;
        [Nn]* ) exit 0;;
        * ) echo "Please answer Y (yes) or N (no).";;
    esac
done

if [ -z "1" ]; then
    echo "Error: Toolkit file not specified."
    exit 1
fi

if [ ! -f "$1" ]; then
    echo "Error: Specified toolkit file $1 does not exist."
    exit 1
fi


function removeOldToolkitFromContainer
{
    echo ""
    echo "############################################################"
    echo "Removing previous toolkit from $1 container"
    docker exec -u i2analyze $1 sh -c "rm -Rf /opt/IBM/i2analyze/toolkit &>/dev/null || true"
}

function installNewDependencies
{
    echo ""
    echo "############################################################"
    echo "Installing new dependencies to $1 container"
	docker exec -u root $1 apt-get install -y net-tools
    echo ""
}

function copyAndExtractToolkit
{
    echo ""
    echo "############################################################"
    echo "Copying the toolkit to $1 container"
    docker cp $2 $1:/opt/IBM/i2analyze.tar.gz
    echo "Changing the permissions on the toolkit tar.gz before extracting it"
	docker exec -u root $1 chown i2analyze:i2analyze /opt/IBM/i2analyze.tar.gz
	echo "Extracting the toolkit tar.gz"
    #Don't extract license file
    docker exec -u i2analyze $1 bsdtar -xpf /opt/IBM/i2analyze.tar.gz -C /opt/IBM/i2analyze --exclude='*license_acknowledgment.txt'
    docker exec -u root $1 rm -f /opt/IBM/i2analyze.tar.gz
    echo ""
}

output "Remove the previous toolkit from the containers"
removeOldToolkitFromContainer admin_client
removeOldToolkitFromContainer zookeeper
removeOldToolkitFromContainer zookeeper2
removeOldToolkitFromContainer zookeeper3
removeOldToolkitFromContainer solr
removeOldToolkitFromContainer solr2
removeOldToolkitFromContainer liberty
removeOldToolkitFromContainer ihs

output "Install new dependencies required by the new toolkit to the containers"
installNewDependencies liberty $1

output "Copy and extract the toolkit to the containers"
copyAndExtractToolkit admin_client $1
copyAndExtractToolkit zookeeper $1
copyAndExtractToolkit zookeeper2 $1
copyAndExtractToolkit zookeeper3 $1
copyAndExtractToolkit solr $1
copyAndExtractToolkit solr2 $1
copyAndExtractToolkit liberty $1
copyAndExtractToolkit ihs $1

popd
