#!/bin/bash
# i2, i2 Group, the i2 Group logo, and i2group.com are trademarks of N.Harris Computer Corporation.
# © N.Harris Computer Corporation (2022)
#
# SPDX short identifier: MIT

#####################################################################################
#                                                                                   #
#  Script to restart all the containers.                                            #
#                                                                                   #
#  Usage : restartContainers                                                        #
#                                                                                   #
#####################################################################################

set -e

. utils/variables

pushd ..

. ${UTILS_PATH}/functions

output "Stopping existing containers if still running"
docker stop zookeeper zookeeper2 zookeeper3 solr solr2 liberty db2 sqlserver admin_client ihs etl_client connector &>/dev/null || true

output "Starting existing containers"
docker start zookeeper zookeeper2 zookeeper3 &>/dev/null || true
# SSH process needs to start first and as root
docker exec -u root zookeeper service ssh start &>/dev/null || true
docker exec -u root zookeeper2 service ssh start &>/dev/null || true
docker exec -u root zookeeper3 service ssh start &>/dev/null || true
docker start solr solr2 liberty db2 sqlserver admin_client ihs etl_client connector &>/dev/null || true
