#!/bin/bash
#/********************************************************************************
# * (C) Copyright IBM Corporation 2018, 2019.
# *
# * This program and the accompanying materials are made available under the
# * terms of the Eclipse Public License 2.0 which is available at
# * http://www.eclipse.org/legal/epl-2.0.
# *
# * SPDX-License-Identifier: EPL-2.0
# *
# ********************************************************************************/

#####################################################################################
#                                                                                   #
#  Script to restart all the servers                                                #
#                                                                                   #
#  Usage : restartContainers                                                        #
#                                                                                   #
#####################################################################################

docker stop zookeeper solr solr2 liberty db2 ihs etl_client admin_client connector

docker start zookeeper
# SSH process needs to start first and as root
docker exec -u root zookeeper service ssh start

docker start solr solr2 liberty db2 ihs etl_client admin_client connector
