#!/bin/bash
#/********************************************************************************
# * (C) Copyright IBM Corporation 2018, 2020.
# *
# * This program and the accompanying materials are made available under the
# * terms of the Eclipse Public License 2.0 which is available at
# * http://www.eclipse.org/legal/epl-2.0.
# *
# * SPDX-License-Identifier: EPL-2.0
# *
# ********************************************************************************/

#####################################################################################
#                                                                                   #
#  Script to configure an SSH tunnel to secure ZooKeeper communications.            #
#                                                                                   #
#  Usage : setupTunneling                                                           #
#                                                                                   #
#####################################################################################

set -e

. utils/variables

pushd ..

. ${UTILS_PATH}/functions

pushd ${SCRIPTS_PATH}
. updateServerConfigurations tunneling
popd

output "Stopping Liberty"
docker exec -u i2analyze liberty /opt/IBM/i2analyze/toolkit/scripts/setup -t stopLiberty

output "Set the password for the i2analyze user in the zookeeper container"
runCommandUntilSuccess "docker exec -u root -it zookeeper passwd i2analyze"

output "Configuring an SSH tunnel to ZooKeeper"
docker exec -u root zookeeper service ssh start

output "Generating and installing the SSH key for the solr container"
runCommandUntilSuccess "docker exec -u i2analyze -it solr ssh-keygen -t rsa"
runCommandUntilSuccess "docker exec -u i2analyze -it solr ssh-copy-id i2analyze@zookeeper"
output "Generating and installing the SSH key for the solr2 container"
runCommandUntilSuccess "docker exec -u i2analyze -it solr2 ssh-keygen -t rsa"
runCommandUntilSuccess "docker exec -u i2analyze -it solr2 ssh-copy-id i2analyze@zookeeper"
output "Generating and installing the SSH key for the admin_client container"
runCommandUntilSuccess "docker exec -u i2analyze -it admin_client ssh-keygen -t rsa"
runCommandUntilSuccess "docker exec -u i2analyze -it admin_client ssh-copy-id i2analyze@zookeeper"
output "Generating and installing the SSH key for the liberty container"
runCommandUntilSuccess "docker exec -u i2analyze -it liberty ssh-keygen -t rsa"
runCommandUntilSuccess "docker exec -u i2analyze -it liberty ssh-copy-id i2analyze@zookeeper"

# Creating the tunnels
output "Creating the liberty tunnel"
docker exec -u i2analyze -d liberty ssh -4 i2analyze@zookeeper -L 9983:zookeeper:9983 -N
output "Creating the solr tunnel"
docker exec -u i2analyze -d solr ssh -4 i2analyze@zookeeper -L 9983:zookeeper:9983 -N
output "Creating the solr2 tunnel"
docker exec -u i2analyze -d solr2 ssh -4 i2analyze@zookeeper -L 9983:zookeeper:9983 -N
output "Creating the admin_client tunnel"
docker exec -u i2analyze -d admin_client ssh -4 i2analyze@zookeeper -L 9983:zookeeper:9983 -N

#Ensure the tunneling is in the startupExt script so docker stop and start commands work as expected
docker exec -u root solr sh -c "echo \"ssh -4 -f i2analyze@zookeeper -L 9983:zookeeper:9983 -N && /opt/IBM/i2analyze/toolkit/scripts/setup -t startSolrNodes --hostname solr || echo \"Error starting Solr node in solr\"\" > /opt/IBM/startupExt"
docker exec -u root solr2 sh -c "echo \"ssh -4 -f i2analyze@zookeeper -L 9983:zookeeper:9983 -N && /opt/IBM/i2analyze/toolkit/scripts/setup -t startSolrNodes --hostname solr2 || echo \"Error starting Solr node in solr2\"\" > /opt/IBM/startupExt"
docker exec -u root admin_client sh -c "echo \"ssh -4 -f i2analyze@zookeeper -L 9983:zookeeper:9983 -N || echo \"Error starting admin_client\"\" > /opt/IBM/startupExt"
docker exec -u root liberty sh -c "echo \"ssh -4 -f i2analyze@zookeeper -L 9983:zookeeper:9983 -N && export JAVA_HOME=/opt/IBM/i2analyze/deploy/java && /opt/IBM/i2analyze/toolkit/scripts/setup -t startLiberty || echo \"Error starting Liberty\"\" > /opt/IBM/startupExt"
docker exec -u root zookeeper sh -c "echo \"/opt/IBM/i2analyze/toolkit/scripts/setup -t createAndUploadSolrConfig --hostname 127.0.0.1 || echo \"Error starting Zookeeper host in 127.0.0.1\"\" > /opt/IBM/startupExt"

output "Uploading the Solr configuration to the ZooKeeper server"
docker exec -u i2analyze zookeeper /opt/IBM/i2analyze/toolkit/scripts/setup -t createAndUploadSolrConfig --hostname 127.0.0.1

output "Restarting ZooKeeper and Solr"
docker exec -u i2analyze zookeeper /opt/IBM/i2analyze/toolkit/scripts/setup -t restartZkHosts --hostname 127.0.0.1

docker exec -u i2analyze -t solr /opt/IBM/i2analyze/toolkit/scripts/setup -t restartSolrNodes --hostname solr

docker exec -u i2analyze -t solr2 /opt/IBM/i2analyze/toolkit/scripts/setup -t restartSolrNodes --hostname solr2

output "Starting Liberty"
docker exec -u i2analyze liberty /opt/IBM/i2analyze/toolkit/scripts/setup -t startLiberty

popd

