#!/bin/bash
#/********************************************************************************
# * (C) Copyright IBM Corporation 2018, 2019.
# *
# * This program and the accompanying materials are made available under the
# * terms of the Eclipse Public License 2.0 which is available at
# * http://www.eclipse.org/legal/epl-2.0.
# *
# * SPDX-License-Identifier: EPL-2.0
# *
# ********************************************************************************/

#####################################################################################
#                                                                                   #
#  Script to update the configuration on all containers                             #
#                                                                                   #
#  Usage : updateServerConfigurations [<configModsName>]                            #
#                                                                                   #
#####################################################################################

. utils/variables

pushd ..

. ${UTILS_PATH}/functions

configModsName=$1

if [[ -z "$configModsName" ]]; then
    echo "Error: Configuration not specified."
    exit 1
fi

if [[ ! -d "${CONFIG_MODS_PATH}/$configModsName" ]]; then
    echo "Error: Specified configuration $configModsName does not exist."
    exit 1
fi

output "Copy the specified configuration to each container"
#Copy Modifications
docker cp "${CONFIG_MODS_PATH}/${configModsName}/." admin_client:/opt/IBM/i2analyze/toolkit/configuration
docker cp "${CONFIG_MODS_PATH}/${configModsName}/." ihs:/opt/IBM/i2analyze/toolkit/configuration
docker cp "${CONFIG_MODS_PATH}/${configModsName}/." liberty:/opt/IBM/i2analyze/toolkit/configuration
docker cp "${CONFIG_MODS_PATH}/${configModsName}/." zookeeper:/opt/IBM/i2analyze/toolkit/configuration
docker cp "${CONFIG_MODS_PATH}/${configModsName}/." solr:/opt/IBM/i2analyze/toolkit/configuration
docker cp "${CONFIG_MODS_PATH}/${configModsName}/." solr2:/opt/IBM/i2analyze/toolkit/configuration

# Make sure the credentials file is up-to-date
docker cp "${DEFAULT_CONFIG_PATH}/environment/credentials.properties" admin_client:/opt/IBM/i2analyze/toolkit/configuration/environment/credentials.properties
docker cp "${DEFAULT_CONFIG_PATH}/environment/credentials.properties" ihs:/opt/IBM/i2analyze/toolkit/configuration/environment/credentials.properties
docker cp "${DEFAULT_CONFIG_PATH}/environment/credentials.properties" liberty:/opt/IBM/i2analyze/toolkit/configuration/environment/credentials.properties
docker cp "${DEFAULT_CONFIG_PATH}/environment/credentials.properties" zookeeper:/opt/IBM/i2analyze/toolkit/configuration/environment/credentials.properties
docker cp "${DEFAULT_CONFIG_PATH}/environment/credentials.properties" solr:/opt/IBM/i2analyze/toolkit/configuration/environment/credentials.properties
docker cp "${DEFAULT_CONFIG_PATH}/environment/credentials.properties" solr2:/opt/IBM/i2analyze/toolkit/configuration/environment/credentials.properties

#Change the ownership of the copied files
docker exec -u root liberty chown -R i2analyze:db2iusr1 /opt/IBM/i2analyze/toolkit/configuration
docker exec -u root admin_client chown -R i2analyze:db2iusr1 /opt/IBM/i2analyze/toolkit/configuration
docker exec -u root zookeeper chown -R i2analyze:i2analyze /opt/IBM/i2analyze/toolkit/configuration
docker exec -u root solr chown -R i2analyze:i2analyze /opt/IBM/i2analyze/toolkit/configuration
docker exec -u root solr2 chown -R i2analyze:i2analyze /opt/IBM/i2analyze/toolkit/configuration
docker exec -u root ihs chown -R i2analyze:i2analyze /opt/IBM/i2analyze/toolkit/configuration

popd
