#!/bin/bash
#/********************************************************************************
# * (C) Copyright IBM Corporation 2018, 2020.
# *
# * This program and the accompanying materials are made available under the
# * terms of the Eclipse Public License 2.0 which is available at
# * http://www.eclipse.org/legal/epl-2.0.
# *
# * SPDX-License-Identifier: EPL-2.0
# *
# ********************************************************************************/

#####################################################################################
#                                                                                   #
#  Script to upgrade a distributed deployment of i2 Analyze.                        #
#  Ensure that your containers already have the new version of the toolkit          #
#  installed and that you have copied your previous configuration to the containers.#
#                                                                                   #
#  Usage : upgradeDeployment [<dbDialect>]                                          #
#  Defaults to current dialect                                                      #
#                                                                                   #
#####################################################################################

set -e

. utils/variables

pushd ..

. ${UTILS_PATH}/functions
dbDialect=${1:-${DB_DIALECT}}

output "Upgrading the previous configuration"
docker exec -t -u i2analyze admin_client /opt/IBM/i2analyze/toolkit/scripts/setup -t upgradeConfiguration

output "Copying the upgraded configuration from the admin_client container to your local machine"
rm -rf ${CONFIG_MODS_PATH}/${dbDialect}/configuration_upgraded &>/dev/null || true
docker cp admin_client:/opt/IBM/i2analyze/toolkit/configuration ${CONFIG_MODS_PATH}/${dbDialect}/configuration_upgraded

output "Copying the upgraded configuration to each container"

pushd ${SCRIPTS_PATH}
. updateServerConfigurations configuration_upgraded ${dbDialect}
popd

output "Upgrading Zookeeper"
docker exec -u i2analyze zookeeper /opt/IBM/i2analyze/toolkit/scripts/setup -t upgradeZookeeper --hostname zookeeper

output "Upgrading Solr"
docker exec -u i2analyze solr /opt/IBM/i2analyze/toolkit/scripts/setup -t upgradeSolr --hostname solr
docker exec -u i2analyze solr2 /opt/IBM/i2analyze/toolkit/scripts/setup -t upgradeSolr --hostname solr2

output "Upgrading the Information Store database"
docker exec -u i2analyze admin_client /opt/IBM/i2analyze/toolkit/scripts/setup -t upgradeDatabases --hostname admin_client

output "Starting ZooKeeper and uploading new configuration"
docker exec -u i2analyze zookeeper /opt/IBM/i2analyze/toolkit/scripts/setup -t startZkHosts --hostname zookeeper
docker exec -u i2analyze admin_client /opt/IBM/i2analyze/toolkit/scripts/setup -t createAndUploadSolrConfig --hostname admin_client

output "Starting Solr"
docker exec -u i2analyze solr /opt/IBM/i2analyze/toolkit/scripts/setup -t startSolr --hostname solr
docker exec -u i2analyze solr2 /opt/IBM/i2analyze/toolkit/scripts/setup -t startSolr --hostname solr2

output "Upgrading the Solr collection"
docker exec -u i2analyze admin_client /opt/IBM/i2analyze/toolkit/scripts/setup -t upgradeSolrCollections --hostname admin_client

output "Upgrading Liberty"
docker exec -t -u i2analyze liberty /opt/IBM/i2analyze/toolkit/scripts/setup -t upgradeLiberty

output "Starting Liberty"
docker exec -u i2analyze liberty /opt/IBM/i2analyze/toolkit/scripts/setup -t startLiberty

popd
