#!/bin/bash
# i2, i2 Group, the i2 Group logo, and i2group.com are trademarks of N.Harris Computer Corporation.
# © N.Harris Computer Corporation (2022)
#
# SPDX short identifier: MIT

#####################################################################################
#                                                                                   #
#  Script to set up the key stores used for SSL.                                    #
#                                                                                   #
#####################################################################################
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/IBM/HTTPServer/gsk8/lib64
cd /opt/i2/keys/stores
/opt/IBM/HTTPServer/gsk8/bin/gsk8capicmd_64 -keydb -stashpw -db i2-ihs-keystore.kdb
/opt/IBM/HTTPServer/gsk8/bin/gsk8capicmd_64 -keydb -stashpw -db i2-db2-truststore.kdb
