#!/bin/bash
# i2, i2 Group, the i2 Group logo, and i2group.com are trademarks of N.Harris Computer Corporation.
# © N.Harris Computer Corporation (2022)
#
# SPDX short identifier: MIT

#####################################################################################
#                                                                                   #
#  Script to ingest data using the etl_client                                       #
#  sql_server_image for the Microsoft SQL Server server                             #
#                                                                                   #
#####################################################################################

# $1 - command to run
function runCommandUntilSuccess
{
    set +e

    eval $1
    while [ $? -ne 0 ]; do
        eval $1
    done

    set -e
}

cd /opt/i2/i2analyze/etltoolkit

echo "Enter the password that you specified for db.infostore.password in the credentials.properties file"
read -sp "Password: " PASSWORD

echo "Load data"

#create an entity staging table
/opt/i2/i2analyze/etltoolkit/createInformationStoreStagingTable -stid ET5 -sn IS_Staging -tn E_Person

#create a link staging table
/opt/i2/i2analyze/etltoolkit/createInformationStoreStagingTable -stid LAS1 -sn IS_Staging -tn L_Associate

#populate the newly created E_Person staging table
bcp IS_Staging.E_Person in "/opt/i2/i2analyze/example/person.csv" -f "/opt/i2/i2analyze/example/person.fmt" -F 2 -U i2analyze -S "sqlserver,1433" -d ISTORE -P "${PASSWORD}"

#populate the newly created L_Associate staging table
bcp IS_Staging.L_Associate in "/opt/i2/i2analyze/example/person_association_person.csv" -f "/opt/i2/i2analyze/example/person_association_person.fmt" -F 2 -U i2analyze -S "sqlserver,1433" -d ISTORE -P "${PASSWORD}"

#create the ingestion source
./addInformationStoreIngestionSource -n REMOTE -d "Remote ingestion source"

#ingest from the E_Person staging table to the InformationStore
./ingestInformationStoreRecords -imf /opt/i2/i2analyze/example/mapping.xml -imid Person

#ingest from the L_Associate staging table to the InformationStore
./ingestInformationStoreRecords -imf /opt/i2/i2analyze/example/mapping.xml -imid Associate

echo "Cleaning staging tables"
sqlcmd -U i2analyze -P "${PASSWORD}" -S "sqlserver,1433" -d ISTORE -Q "TRUNCATE TABLE IS_Staging.E_Person; TRUNCATE TABLE IS_Staging.L_Associate;"
