#!/bin/bash
# MIT License
#
# Copyright (c) 2022, N. Harris Computer Corporation
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

#####################################################################################
#                                                                                   #
#  Functions                                                                        #
#                                                                                   #
#####################################################################################

set -e

function output
{
  echo ""
  echo "############################################################"
  echo "## $1"
  echo "############################################################"
}

function header
{
    echo ""
    echo "-----------------------------------------------------------"
    echo "-----------------------------------------------------------"
    echo "-- $1"
    echo "-----------------------------------------------------------"
    echo "-----------------------------------------------------------"
}

function waitForContainer() {
    echo $1
    attempt=0
    success=0
    while [ $attempt -le 100 ] && [ $success -eq 0 ]; do
        attempt=$(( $attempt + 1 ))
        echo "Waiting for container to start (attempt: $attempt)..."
        result=$(docker logs "$1")
        if echo "$result" | grep -q "$2" ; then
          echo "Container $1 has started"
          success=1
          break
        elif [ -n "$3" ] ; then
          if echo "$result" | grep -q "$3" ; then
            echo "ERROR: Container $1 did NOT start"
            exit 1
          fi
        fi
        sleep 10
    done
    if [ $success -eq 0 ]; then
      echo "ERROR: Container $1 did NOT start"
      exit 1
    fi
}

function containerExists()
{
    if [ "$(docker ps -aq -f name=^/${1}$)" ]; then
        echo "1"
    else
        echo "0"
    fi
}

# $1 - command to run
function runCommandUntilSuccess
{
    set +e

    eval $1
    while [ $? -ne 0 ]; do
        eval $1
    done

    set -e
}

# $1 - container
# $2 - command to run
function runDockerExecWithSSLPassword
{
    docker exec -u root -t -e SSL_PASSWORD=$SSL_PASSWORD $1 $2
}
