#!/bin/bash
#/********************************************************************************
# * (C) Copyright IBM Corporation 2018, 2020.
# *
# * This program and the accompanying materials are made available under the
# * terms of the Eclipse Public License 2.0 which is available at
# * http://www.eclipse.org/legal/epl-2.0.
# *
# * SPDX-License-Identifier: EPL-2.0
# *
# ********************************************************************************/

#####################################################################################
#                                                                                   #
#  Functions                                                                        #
#                                                                                   #
#####################################################################################

set -e

function output
{
  echo ""
  echo "############################################################"
  echo "## $1"
  echo "############################################################"
}

function header
{
    echo ""
    echo "-----------------------------------------------------------"
    echo "-----------------------------------------------------------"
    echo "-- $1"
    echo "-----------------------------------------------------------"
    echo "-----------------------------------------------------------"
}

function waitForContainer() {
    echo $1
    attempt=0
    success=0
    while [ $attempt -le 100 ] && [ $success -eq 0 ]; do
        attempt=$(( $attempt + 1 ))
        echo "Waiting for container to start (attempt: $attempt)..."
        result=$(docker logs "$1")
        if echo "$result" | grep -q "$2" ; then
          echo "Container $1 has started"
          success=1
          break
        elif [ -n "$3" ] ; then
          if echo "$result" | grep -q "$3" ; then
            echo "ERROR: Container $1 did NOT start"
            exit 1
          fi
        fi
        sleep 10
    done
    if [ $success -eq 0 ]; then
      echo "ERROR: Container $1 did NOT start"
      exit 1
    fi
}

function containerExists()
{
    if [ "$(docker ps -aq -f name=^/${1}$)" ]; then
        echo "1"
    else
        echo "0"
    fi
}

# $1 - command to run
function runCommandUntilSuccess
{
    set +e

    eval $1
    while [ $? -ne 0 ]; do
        eval $1
    done

    set -e
}
