#!/bin/bash
#/********************************************************************************
# * (C) Copyright IBM Corporation 2018, 2019.
# *
# * This program and the accompanying materials are made available under the
# * terms of the Eclipse Public License 2.0 which is available at
# * http://www.eclipse.org/legal/epl-2.0.
# *
# * SPDX-License-Identifier: EPL-2.0
# *
# ********************************************************************************/

#####################################################################################
#                                                                                   #
#  Variables                                                                        #
#                                                                                   #
#####################################################################################

SRC_DIR=.

SCRIPTS_PATH=${SRC_DIR}/scripts
UTILS_PATH=${SCRIPTS_PATH}/utils
SSL_SCRIPTS_PATH=${SCRIPTS_PATH}/ssl
IMAGES_PATH=${SRC_DIR}/images
DEFAULT_CONFIG_PATH=${SRC_DIR}/configuration
BASE_CONFIG_PATH=${IMAGES_PATH}/common/ubuntu_toolkit/configuration
CONFIG_MODS_PATH=${SRC_DIR}/configuration_mods
NON_BASIC_CONTAINERS="ihs etl_client connector"
I2ANALYZE_VERSION=4.3.1.0

# Dynamic variables

DB_DIALECT=$(docker ps -a | grep -o "liberty_\w*_image" | cut -d_ -f2)
DB_DIALECT=${DB_DIALECT:-sqlserver}
