#!/bin/bash
# i2, i2 Group, the i2 Group logo, and i2group.com are trademarks of N.Harris Computer Corporation.
# © N.Harris Computer Corporation (2022-2023)
#
# SPDX short identifier: MIT

#####################################################################################
#                                                                                   #
#  Variables                                                                        #
#                                                                                   #
#####################################################################################

SRC_DIR=.

SCRIPTS_PATH=${SRC_DIR}/scripts
UTILS_PATH=${SCRIPTS_PATH}/utils
SSL_SCRIPTS_PATH=${SCRIPTS_PATH}/ssl
IMAGES_PATH=${SRC_DIR}/images
DEFAULT_CONFIG_PATH=${SRC_DIR}/configuration
BASE_CONFIG_PATH=${IMAGES_PATH}/common/ubuntu_toolkit/configuration
CONFIG_MODS_PATH=${SRC_DIR}/configuration_mods
NON_BASIC_CONTAINERS="etl_client connector"

# Dynamic variables

DB_DIALECT=$(docker ps -a | grep -o "liberty_\w*_image" | cut -d_ -f2)
DB_DIALECT=${DB_DIALECT:-sqlserver}
