#!/bin/bash
# i2, i2 Group, the i2 Group logo, and i2group.com are trademarks of N.Harris Computer Corporation.
# © N.Harris Computer Corporation (2022-2023)
#
# SPDX short identifier: MIT

#####################################################################################
#                                                                                   #
#  Script to install the DB2 server with the db2server.rsp in the                   #
#  db2_image for the DB2 server                                                     #
#                                                                                   #
#####################################################################################

#When the installer fails its aggressively sends a SIGHUP.
#Suppress this error.
trap '' SIGHUP
/opt/IBM/server_dec/db2setup -r /opt/IBM/db2server.rsp

if [ ! $? -eq 0 ]; then
   echo Trying again
   trap - SIGHUP
   #The second time works. This appears to be a docker issue
   # with how the installer is using systemd.
   /opt/IBM/server_dec/db2setup -r /opt/IBM/db2server.rsp
fi
