#!/bin/bash
# i2, i2 Group, the i2 Group logo, and i2group.com are trademarks of N.Harris Computer Corporation.
# © N.Harris Computer Corporation (2022-2023)
#
# SPDX short identifier: MIT
set -e

# Apache gets grumpy about PID files pre-existing
rm -f /opt/IBM/HTTPServer/logs/httpd.pid

if [ -f /opt/IBM/HTTPServer/bin/envvars ]; then
  . /opt/IBM/HTTPServer/bin/envvars
fi

exec /opt/IBM/HTTPServer/bin/httpd -d /opt/IBM/HTTPServer -DFOREGROUND "$@"