#!/bin/bash
#/********************************************************************************
# * (C) Copyright IBM Corporation 2018, 2019.
# *
# * This program and the accompanying materials are made available under the
# * terms of the Eclipse Public License 2.0 which is available at
# * http://www.eclipse.org/legal/epl-2.0.
# *
# * SPDX-License-Identifier: EPL-2.0
# *
# ********************************************************************************/

#####################################################################################
#                                                                                   #
#  Script to sign certificate.                                                      #
#                                                                                   #
#####################################################################################

type=$1
in=$2
out=$3

#Original CA.key was made using these commands
#openssl req -new -sha256 -nodes -newkey rsa:4096 -keyout CA.key -out CA.csr
#openssl x509 -req -sha256 -extfile x509.ext -extensions ca -in CA.csr -signkey CA.key -days 1095 -out CA.cer


cd opt/IBM/ca

#Signs the the request creating a new certificate
openssl x509 -req -sha256 -CA CA.cer -CAkey CA.key -days 730 -CAcreateserial -CAserial CA.srl -extfile x509.ext -extensions $type -in $in -out $out
