#!/bin/bash
#/********************************************************************************
# * (C) Copyright IBM Corporation 2018, 2021.
# *
# * This program and the accompanying materials are made available under the
# * terms of the Eclipse Public License 2.0 which is available at
# * http://www.eclipse.org/legal/epl-2.0.
# *
# * SPDX-License-Identifier: EPL-2.0
# *
# ********************************************************************************/
set -e

# Apache gets grumpy about PID files pre-existing
rm -f /opt/IBM/HTTPServer/logs/httpd.pid

if [ -f /opt/IBM/HTTPServer/bin/envvars ]; then
  . /opt/IBM/HTTPServer/bin/envvars
fi

exec /opt/IBM/HTTPServer/bin/httpd -d /opt/IBM/HTTPServer -DFOREGROUND "$@"