#!/bin/bash
# i2, i2 Group, the i2 Group logo, and i2group.com are trademarks of N.Harris Computer Corporation.
# © N.Harris Computer Corporation (2022)
#
# SPDX short identifier: MIT

#####################################################################################
#                                                                                   #
#  Script to ingest data using the etl_client                                       #
#  postgres_server_image for the PostGreSQL Server server                           #
#                                                                                   #
#####################################################################################

# $1 - command to run
function runCommandUntilSuccess
{
    set +e

    eval $1
    while [ $? -ne 0 ]; do
        eval $1
    done

    set -e
}

cd /opt/i2/i2analyze/etltoolkit

echo "Enter the password that you specified for db.infostore.password in the credentials.properties file"
read -sp "Password: " POSTGRES_PASSWORD

echo "Load data"

#create an entity staging table
/opt/i2/i2analyze/etltoolkit/createInformationStoreStagingTable -stid ET5 -sn IS_Staging -tn E_Person

#create a link staging table
/opt/i2/i2analyze/etltoolkit/createInformationStoreStagingTable -stid LAS1 -sn IS_Staging -tn L_Associate

#populate the newly created E_Person staging table
PGPASSWORD="${POSTGRES_PASSWORD}" psql -w -X -q --set=client_min_messages=warning -h "postgres" -p "5432" -d "ISTORE" -U i2analyze -c "\COPY IS_Staging.E_Person (source_id,p_date_of_birth,p_first_given_name,p_family_name,p_occupation,p_gender,source_ref_source_type,source_ref_source_location) FROM '/opt/i2/i2analyze/example/person.csv' CSV HEADER ENCODING 'UTF8' NULL AS ''"

#populate the newly created L_Associate staging table
PGPASSWORD="${POSTGRES_PASSWORD}" psql -w -X -q --set=client_min_messages=warning -h "postgres" -p "5432" -d "ISTORE" -U i2analyze -c "\COPY IS_Staging.L_Associate (source_id,from_source_id,to_source_id,p_association_type,direction) FROM '/opt/i2/i2analyze/example/person_association_person.csv' CSV HEADER ENCODING 'UTF8' NULL AS ''"

#create the ingestion source
./addInformationStoreIngestionSource -n REMOTE -d "Remote ingestion source"

#ingest from the E_Person staging table to the InformationStore
./ingestInformationStoreRecords -imf /opt/i2/i2analyze/example/mapping.xml -imid Person

#ingest from the L_Associate staging table to the InformationStore
./ingestInformationStoreRecords -imf /opt/i2/i2analyze/example/mapping.xml -imid Associate

echo "Cleaning staging tables"
PGPASSWORD="${POSTGRES_PASSWORD}" psql -w -X -q --set=client_min_messages=warning -h "postgres" -p "5432" -d "ISTORE" -U i2analyze -c "TRUNCATE TABLE IS_Staging.E_Person; TRUNCATE TABLE IS_Staging.L_Associate;"
