#!/bin/bash
#/********************************************************************************
# * (C) Copyright IBM Corporation 2018, 2020.
# *
# * This program and the accompanying materials are made available under the
# * terms of the Eclipse Public License 2.0 which is available at
# * http://www.eclipse.org/legal/epl-2.0.
# *
# * SPDX-License-Identifier: EPL-2.0
# *
# ********************************************************************************/

#####################################################################################
#                                                                                   #
#  Script to add the signed certificates into their corresponding key store.        #
#                                                                                   #
#  This script is called as part of the createKeysAndStores script.                 #
#                                                                                   #
#####################################################################################

. ${UTILS_PATH}/variables
. ${UTILS_PATH}/functions

dbDialect=${1:-${DB_DIALECT}}

output "Adding the signed certificate to the liberty container"
docker cp ${SRC_DIR}/keys/responses/. liberty:/opt/IBM/keys/responses
runDockerExecWithSSLPassword liberty "/opt/IBM/utils/jks/applyResponse liberty jks"

output "Adding the signed certificate to the admin_client container"
docker cp ${SRC_DIR}/keys/responses/. admin_client:/opt/IBM/keys/responses
runDockerExecWithSSLPassword admin_client "/opt/IBM/utils/jks/applyResponse admin_client jks"

output "Adding the signed 'Jenny' user certificate to the liberty container"
runDockerExecWithSSLPassword liberty "/opt/IBM/utils/jks/applyResponse Jenny"

output "Converting the 'Jenny' user key store to PKCS12 format"
runDockerExecWithSSLPassword liberty "/opt/IBM/utils/jks/convertKeyStore Jenny"
docker cp liberty:/opt/IBM/keys/stores/i2-Jenny-keystore.p12 ${SRC_DIR}/keys/stores/

output "Adding the signed 'Imogen' user certificate to the liberty container"
runDockerExecWithSSLPassword liberty "/opt/IBM/utils/jks/applyResponse Imogen"

output "Converting the 'Imogen' user key store to PKCS12 format"
runDockerExecWithSSLPassword liberty "/opt/IBM/utils/jks/convertKeyStore Imogen"
docker cp liberty:/opt/IBM/keys/stores/i2-Imogen-keystore.p12 ${SRC_DIR}/keys/stores/

output "Adding the signed certificate to the solr container"
docker cp ${SRC_DIR}/keys/responses/. solr:/opt/IBM/keys/responses
runDockerExecWithSSLPassword solr "/opt/IBM/utils/jks/applyResponse solr"

output "Adding the signed certificate to the solr2 container"
docker cp ${SRC_DIR}/keys/responses/. solr2:/opt/IBM/keys/responses
runDockerExecWithSSLPassword solr2 "/opt/IBM/utils/jks/applyResponse solr2"

output "Adding the signed certificate to the zookeeper container"
docker cp ${SRC_DIR}/keys/responses/. zookeeper:/opt/IBM/keys/responses
runDockerExecWithSSLPassword zookeeper "/opt/IBM/utils/jks/applyResponse zookeeper"

output "Adding the signed certificate to the zookeeper2 container"
docker cp ${SRC_DIR}/keys/responses/. zookeeper2:/opt/IBM/keys/responses
runDockerExecWithSSLPassword zookeeper2 "/opt/IBM/utils/jks/applyResponse zookeeper2"

output "Adding the signed certificate to the zookeeper3 container"
docker cp ${SRC_DIR}/keys/responses/. zookeeper3:/opt/IBM/keys/responses
runDockerExecWithSSLPassword zookeeper3 "/opt/IBM/utils/jks/applyResponse zookeeper3"

if [[ $dbDialect == "db2" ]]; then
	output "Adding the signed certificate to the db2 container"
	docker cp ${SRC_DIR}/keys/responses/. db2:/opt/IBM/keys/responses
	runDockerExecWithSSLPassword db2 "/opt/IBM/utils/cms/applyResponse db2"
elif [[ $dbDialect == "sqlserver" ]]; then
	output "Adding the signed certificate to the sqlserver container"
	docker cp ${SRC_DIR}/keys/responses/. sqlserver:/opt/IBM/keys/responses
fi

output "Adding the signed certificate to the ihs container"
docker cp ${SRC_DIR}/keys/responses/. ihs:/opt/IBM/keys/responses
runDockerExecWithSSLPassword ihs "/opt/IBM/utils/cms/applyResponse ihs"

output "Adding the signed certificate to the connector container"
docker cp ${SRC_DIR}/keys/responses/. connector:/opt/IBM/keys/responses
