#!/bin/bash
#/********************************************************************************
# * (C) Copyright IBM Corporation 2018, 2020.
# *
# * This program and the accompanying materials are made available under the
# * terms of the Eclipse Public License 2.0 which is available at
# * http://www.eclipse.org/legal/epl-2.0.
# *
# * SPDX-License-Identifier: EPL-2.0
# *
# ********************************************************************************/

#####################################################################################
#                                                                                   #
#  Script to add the signed certificates into their corresponding key store.        #
#                                                                                   #
#  This script is called as part of the createKeysAndStores script.                 #
#                                                                                   #
#####################################################################################

. ${UTILS_PATH}/variables

dbDialect=${1:-${DB_DIALECT}}

output "Adding the signed certificate to the liberty container"
docker cp ${SRC_DIR}/keys/responses/. liberty:/opt/IBM/keys/responses
docker exec -u root -it liberty /opt/IBM/utils/jks/applyResponse liberty

output "Adding the signed 'Jenny' user certificate to the liberty container"
docker exec -u root -it liberty /opt/IBM/utils/jks/applyResponse Jenny

output "Converting the 'Jenny' user key store to PKCS12 format"
docker exec -u root -it liberty /opt/IBM/utils/jks/convertKeyStore Jenny
docker cp liberty:/opt/IBM/keys/stores/i2-Jenny-keystore.p12 ${SRC_DIR}/keys/stores/

output "Adding the signed 'Imogen' user certificate to the liberty container"
docker exec -u root -it liberty /opt/IBM/utils/jks/applyResponse Imogen

output "Converting the 'Imogen' user key store to PKCS12 format"
docker exec -u root -it liberty /opt/IBM/utils/jks/convertKeyStore Imogen
docker cp liberty:/opt/IBM/keys/stores/i2-Imogen-keystore.p12 ${SRC_DIR}/keys/stores/

output "Adding the signed certificate to the solr container"
docker cp ${SRC_DIR}/keys/responses/. solr:/opt/IBM/keys/responses
docker exec -u root -it solr /opt/IBM/utils/jks/applyResponse solr

output "Adding the signed certificate to the solr2 container"
docker cp ${SRC_DIR}/keys/responses/. solr2:/opt/IBM/keys/responses
docker exec -u root -it solr2 /opt/IBM/utils/jks/applyResponse solr2

if [[ $dbDialect == "db2" ]]; then
	output "Adding the signed certificate to the db2 container"
	docker cp ${SRC_DIR}/keys/responses/. db2:/opt/IBM/keys/responses
	docker exec -u root -it db2 /opt/IBM/utils/cms/applyResponse db2
elif [[ $dbDialect == "sqlserver" ]]; then
	output "Adding the signed certificate to the sqlserver container"
	docker cp ${SRC_DIR}/keys/responses/. sqlserver:/opt/IBM/keys/responses
fi

output "Adding the signed certificate to the ihs container"
docker cp ${SRC_DIR}/keys/responses/. ihs:/opt/IBM/keys/responses
docker exec -u root -it ihs /opt/IBM/utils/cms/applyResponse ihs

output "Adding the signed certificate to the connector container"
docker cp ${SRC_DIR}/keys/responses/. connector:/opt/IBM/keys/responses
