#!/bin/bash
# i2, i2 Group, the i2 Group logo, and i2group.com are trademarks of N.Harris Computer Corporation.
# © N.Harris Computer Corporation (2022)
#
# SPDX short identifier: MIT

#####################################################################################
#                                                                                   #
#  Script to create key stores, trust stores, and certificate signing requests.     #
#                                                                                   #
#  This script is called as part of the createKeysAndStores script.                 #
#                                                                                   #
#####################################################################################

. ${UTILS_PATH}/variables
. ${UTILS_PATH}/functions

dbDialect=${1:-${DB_DIALECT}}

output "Removing any previous keys, if they exist"
rm -rf ${SRC_DIR}/keys
mkdir -p ${SRC_DIR}/keys/requests
mkdir -p ${SRC_DIR}/keys/stores

output "Adding the CA certificate to containers"
docker cp ${IMAGES_PATH}/common/ca/ca/CA.cer liberty:/opt/i2/utils/keys/CA.cer
docker cp ${IMAGES_PATH}/common/ca/ca/CA.cer solr:/opt/i2/utils/keys/CA.cer
docker cp ${IMAGES_PATH}/common/ca/ca/CA.cer solr2:/opt/i2/utils/keys/CA.cer
docker cp ${IMAGES_PATH}/common/ca/ca/CA.cer zookeeper:/opt/i2/utils/keys/CA.cer
docker cp ${IMAGES_PATH}/common/ca/ca/CA.cer zookeeper2:/opt/i2/utils/keys/CA.cer
docker cp ${IMAGES_PATH}/common/ca/ca/CA.cer zookeeper3:/opt/i2/utils/keys/CA.cer
docker cp ${IMAGES_PATH}/common/ca/ca/CA.cer $dbDialect:/opt/i2/utils/keys/CA.cer
docker cp ${IMAGES_PATH}/common/ca/ca/CA.cer admin_client:/opt/i2/utils/keys/CA.cer
if [ "$(docker ps -q -f name=etl_client)" ]; then
  docker cp ${IMAGES_PATH}/common/ca/ca/CA.cer etl_client:/opt/i2/utils/keys/CA.cer
fi

if [ "$(docker ps -q -f name=connector)" ]; then
  docker cp ${IMAGES_PATH}/common/ca/ca/CA.cer connector:/opt/i2/utils/keys/CA.cer
fi

if [ "$(docker ps -q -f name=ihs)" ]; then
  docker cp ${IMAGES_PATH}/common/ca/ca/CA.cer ihs:/opt/i2/utils/keys/CA.cer
fi

output "Creating the liberty container key store and certificate signing request"
docker exec -u root -t liberty rm -rf /opt/i2/keys
runDockerExecWithSSLPassword liberty "/opt/i2/utils/jks/createCSR liberty jks"

output "Creating 'Jenny' user key store and certificate signing request"
runDockerExecWithSSLPassword liberty "/opt/i2/utils/jks/createCSR Jenny Jenny Jenny"

output "Creating 'Imogen' user key store and certificate signing request"
runDockerExecWithSSLPassword liberty "/opt/i2/utils/jks/createCSR Imogen Imogen Imogen"

#Copy the liberty and users certificates signing requests to the local machine
docker cp liberty:/opt/i2/keys/requests/. ${SRC_DIR}/keys/requests

output "Creating the solr container key store and certificate signing request"
docker exec -u root -t solr rm -rf /opt/i2/keys
runDockerExecWithSSLPassword solr "/opt/i2/utils/jks/createCSR solr"
docker cp solr:/opt/i2/keys/requests/. ${SRC_DIR}/keys/requests

output "Creating the solr2 container key store and certificate signing request"
docker exec -u root -t solr2 rm -rf /opt/i2/keys
runDockerExecWithSSLPassword solr2 "/opt/i2/utils/jks/createCSR solr2"
docker cp solr2:/opt/i2/keys/requests/. ${SRC_DIR}/keys/requests

output "Creating the zookeeper container key store and certificate signing request"
docker exec -u root -t zookeeper rm -rf /opt/i2/keys
runDockerExecWithSSLPassword zookeeper "/opt/i2/utils/jks/createCSR zookeeper"
docker cp zookeeper:/opt/i2/keys/requests/. ${SRC_DIR}/keys/requests

output "Creating the zookeeper2 container key store and certificate signing request"
docker exec -u root -t zookeeper2 rm -rf /opt/i2/keys
runDockerExecWithSSLPassword zookeeper2 "/opt/i2/utils/jks/createCSR zookeeper2"
docker cp zookeeper2:/opt/i2/keys/requests/. ${SRC_DIR}/keys/requests

output "Creating the zookeeper3 container key store and certificate signing request"
docker exec -u root -t zookeeper3 rm -rf /opt/i2/keys
runDockerExecWithSSLPassword zookeeper3 "/opt/i2/utils/jks/createCSR zookeeper3"
docker cp zookeeper3:/opt/i2/keys/requests/. ${SRC_DIR}/keys/requests

case "${dbDialect}" in
  "db2")
    output "Creating the db2 container key store and certificate signing request"
    docker exec -u root -t db2 rm -rf /opt/i2/keys
    runDockerExecWithSSLPassword db2 "/opt/i2/utils/cms/createCSR db2"
    docker cp db2:/opt/i2/keys/requests/. ${SRC_DIR}/keys/requests
    runDockerExecWithSSLPassword db2 "/opt/i2/utils/cms/createTrustStore cms"
    ;;
  "sqlserver")
    output "Creating the sqlserver container key store and certificate signing request"
    docker exec -u root -t sqlserver rm -rf /opt/i2/keys
    runDockerExecWithSSLPassword sqlserver "/opt/i2/utils/openssl/createCSR sqlserver"
    docker cp sqlserver:/opt/i2/keys/requests/. ${SRC_DIR}/keys/requests
    ;;
  "postgres")
    output "Creating the postgres container key store and certificate signing request"
    docker exec -u root -t postgres rm -rf /opt/i2/keys
    runDockerExecWithSSLPassword postgres "/opt/i2/utils/openssl/createCSR postgres"
    docker cp postgres:/opt/i2/keys/requests/. ${SRC_DIR}/keys/requests
    ;;
esac


if [ "$(docker ps -q -f name=ihs)" ]; then
  output "Creating the ihs container key store and certificate signing request"
  docker exec -u root -t ihs rm -rf /opt/i2/keys
  runDockerExecWithSSLPassword ihs "/opt/i2/utils/cms/createCSR ihs"
  docker cp ihs:/opt/i2/keys/requests/. ${SRC_DIR}/keys/requests
  runDockerExecWithSSLPassword ihs "/opt/i2/utils/cms/createTrustStore cms"
fi

output "Creating the admin_client container key store and certificate signing request"
docker exec -u root -t admin_client rm -rf /opt/i2/keys
runDockerExecWithSSLPassword admin_client "/opt/i2/utils/jks/createCSR admin_client jks"
docker cp admin_client:/opt/i2/keys/requests/. ${SRC_DIR}/keys/requests

output "Creating the admin_client container trust stores"
runDockerExecWithSSLPassword admin_client "/opt/i2/utils/jks/createTrustStore admin_client"
if [[ $dbDialect == "db2" ]]; then
	runDockerExecWithSSLPassword admin_client "/opt/i2/utils/cms/createTrustStore db2"
fi

if [ "$(docker ps -q -f name=etl_client)" ]; then
  output "Creating the etl_client container trust store"
  docker exec -u root -t etl_client rm -rf /opt/i2/keys
  docker exec -u root -t etl_client mkdir -p /opt/i2/keys/stores
  if [[ $dbDialect == "db2" ]]; then
    runDockerExecWithSSLPassword etl_client "/opt/i2/utils/cms/createTrustStore db2"
  fi
fi

if [ "$(docker ps -q -f name=connector)" ]; then
  output "Creating i2 Connect connector key store and certificate signing request"
  docker exec -u root -t connector rm -rf /opt/i2/keys
  runDockerExecWithSSLPassword connector "/opt/i2/utils/openssl/createCSR connector"
  docker cp connector:/opt/i2/keys/requests/. ${SRC_DIR}/keys/requests
fi

output "Copy the common trust store to each container"
docker cp admin_client:/opt/i2/keys/stores/i2-jks-truststore.jks ${SRC_DIR}/keys/stores/i2-jks-truststore.jks
docker cp ${SRC_DIR}/keys/stores/i2-jks-truststore.jks liberty:/opt/i2/keys/stores/i2-jks-truststore.jks
docker cp ${SRC_DIR}/keys/stores/i2-jks-truststore.jks solr:/opt/i2/keys/stores/i2-jks-truststore.jks
docker cp ${SRC_DIR}/keys/stores/i2-jks-truststore.jks solr2:/opt/i2/keys/stores/i2-jks-truststore.jks
docker cp ${SRC_DIR}/keys/stores/i2-jks-truststore.jks zookeeper:/opt/i2/keys/stores/i2-jks-truststore.jks
docker cp ${SRC_DIR}/keys/stores/i2-jks-truststore.jks zookeeper2:/opt/i2/keys/stores/i2-jks-truststore.jks
docker cp ${SRC_DIR}/keys/stores/i2-jks-truststore.jks zookeeper3:/opt/i2/keys/stores/i2-jks-truststore.jks
if [ "$(docker ps -q -f name=etl_client)" ]; then
  docker cp ${SRC_DIR}/keys/stores/i2-jks-truststore.jks etl_client:/opt/i2/keys/stores/i2-jks-truststore.jks
fi

#Change the file ownership of the copied files
docker exec -u root liberty chown root:keys /opt/i2/keys/stores/i2-jks-truststore.jks
docker exec -u root solr chown root:keys /opt/i2/keys/stores/i2-jks-truststore.jks
docker exec -u root solr2 chown root:keys /opt/i2/keys/stores/i2-jks-truststore.jks
docker exec -u root zookeeper chown root:keys /opt/i2/keys/stores/i2-jks-truststore.jks
docker exec -u root zookeeper2 chown root:keys /opt/i2/keys/stores/i2-jks-truststore.jks
docker exec -u root zookeeper3 chown root:keys /opt/i2/keys/stores/i2-jks-truststore.jks
if [ "$(docker ps -q -f name=etl_client)" ]; then
  docker exec -u root etl_client chown root:keys /opt/i2/keys/stores/i2-jks-truststore.jks
fi
