#!/bin/bash
# MIT License
#
# Copyright (c) 2022, N. Harris Computer Corporation
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

. /opt/IBM/utils/functions

name=$1

utils=/opt/IBM/utils
keystoreFile=/opt/IBM/keys/stores/i2-${name}-truststore.kdb

if [ -e /opt/ibm/db2/V11.5/gskit/bin/gsk8capicmd_64 ]
then
  gsk=/opt/ibm/db2/V11.5/gskit/bin/gsk8capicmd_64
  export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/home/db2inst1/sqllib/lib64/gskit
elif [ -e /opt/IBM/HTTPServer/gsk8/bin/gsk8capicmd_64 ]
then
  gsk=/opt/IBM/HTTPServer/gsk8/bin/gsk8capicmd_64
  export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/opt/IBM/HTTPServer/gsk8/lib64
elif [ -e /usr/local/ibm/gsk8_64/bin/gsk8capicmd_64 ]
then
  gsk=/usr/local/ibm/gsk8_64/bin/gsk8capicmd_64
  export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/ibm/gsk8_64/lib64
else
  echo "Could not find gsk toolkit"
  exit -1
fi

#Generate new certificate pair
runCommandUntilSuccess "$gsk -keydb -create -db $keystoreFile -pw -genpw -stash"

#Add ca
runCommandUntilSuccess "$gsk -cert -add -db $keystoreFile -stashed -label \"caCer\" -file ${utils}/keys/CA.cer -format binary -trust enable"

#Change ownership to make visible to keys group
chown -R root:keys /opt/IBM/keys
chmod -R 650 /opt/IBM/keys
