#!/bin/bash
# i2, i2 Group, the i2 Group logo, and i2group.com are trademarks of N.Harris Computer Corporation.
# © N.Harris Computer Corporation (2022)
#
# SPDX short identifier: MIT

. /opt/i2/utils/functions

uri=$1

keystoreFile=/opt/i2/keys/stores/i2-${uri}-keystore.kdb
keyName=${uri}key
out=/opt/i2/keys/requests/${uri}-key.csr

if [ -e /opt/ibm/db2/V11.5/gskit/bin/gsk8capicmd_64 ]
then
  gsk=/opt/ibm/db2/V11.5/gskit/bin/gsk8capicmd_64
  export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/home/db2inst1/sqllib/lib64/gskit
elif [ -e /opt/IBM/HTTPServer/gsk8/bin/gsk8capicmd_64 ]
then
  gsk=/opt/IBM/HTTPServer/gsk8/bin/gsk8capicmd_64
  export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/opt/IBM/HTTPServer/gsk8/lib64
elif [ -e /usr/local/ibm/gsk8_64/bin/gsk8capicmd_64 ]
then
  gsk=/usr/local/ibm/gsk8_64/bin/gsk8capicmd_64
  export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/ibm/gsk8_64/lib64
else
  echo "Could not find gsk toolkit"
  exit -1
fi

#Make the requests directory
mkdir -p /opt/i2/keys/requests

#Create the stores directory
mkdir -p /opt/i2/keys/stores

export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/ibm/gsk8_64/lib64

#Generate new certificate pair
runCommandUntilSuccess "$gsk -keydb -create -db $keystoreFile -genpw -stash"

#Create signing request for public certificate
runCommandUntilSuccess "$gsk -certreq -create -db $keystoreFile -label $keyName -sigalg SHA512WithRSA -size 2048 -dn CN=${uri}.eianet -stashed -file $out"

#Change ownership to make visible to keys group
chown -R root:keys /opt/i2/keys
chmod -R 650 /opt/i2/keys
