#!/bin/bash
# i2, i2 Group, the i2 Group logo, and i2group.com are trademarks of N.Harris Computer Corporation.
# © N.Harris Computer Corporation (2022-2023)
#
# SPDX short identifier: MIT

#####################################################################################
#                                                                                   #
#  Script to initialize the etl_client.                                             #
#                                                                                   #
#  Usage : initializeEtlClient enable/disable                                       #
#  The "security" argument will catalog the dbnode and ISTORE database.             #
#  using a secure port and SSL if set to enable. Defaults to disable.               #
#####################################################################################
function output
{
  echo ""
  echo "############################################################"
  echo "## $1"
  echo "############################################################"
}

security=${1:-disable}

echo "Ensure to source the db2profile"
. /home/db2inst1/sqllib/db2profile

db2 uncatalog db ISTORE &>/dev/null
db2 uncatalog node dbnode &>/dev/null

if [ $security = 'enable' ]; then
    output "Cataloguing the dbnode and ISTORE using the secure port and SSL"
    db2 catalog tcpip node dbnode remote db2 server 50001 security SSL
    db2 catalog database ISTORE at node dbnode
else
    output "Cataloguing the dbnode and ISTORE using the non secure port and TCPIP"
    db2 catalog tcpip node dbnode remote db2 server 50000
    db2 catalog database ISTORE at node dbnode
fi

echo "Providing the ETL toolkit with the location of the DB2 client"
sed -i 's/db.installation.dir=\/opt\/IBM\/db2/db.installation.dir=\/home\/db2inst1\/sqllib/g' /opt/i2/i2analyze/etltoolkit/classes/Connection.properties
