#!/bin/bash
# i2, i2 Group, the i2 Group logo, and i2group.com are trademarks of N.Harris Computer Corporation.
# © N.Harris Computer Corporation (2022-2023)
#
# SPDX short identifier: MIT

#####################################################################################
#                                                                                   #
#  Script to add the signed certificates into their corresponding key store.        #
#                                                                                   #
#  This script is called as part of the createKeysAndStores script.                 #
#                                                                                   #
#####################################################################################

. ${UTILS_PATH}/variables
. ${UTILS_PATH}/functions

dbDialect=${1:-${DB_DIALECT}}

output "Adding the signed certificate to the liberty container"
docker cp ${SRC_DIR}/keys/responses/. liberty:/opt/i2/keys/responses
runDockerExecWithSSLPassword liberty "/opt/i2/utils/jks/applyResponse liberty jks"

output "Adding the signed certificate to the admin_client container"
docker cp ${SRC_DIR}/keys/responses/. admin_client:/opt/i2/keys/responses
runDockerExecWithSSLPassword admin_client "/opt/i2/utils/jks/applyResponse admin_client jks"

output "Adding the signed 'Jenny' user certificate to the liberty container"
runDockerExecWithSSLPassword liberty "/opt/i2/utils/jks/applyResponse Jenny"

output "Converting the 'Jenny' user key store to PKCS12 format"
runDockerExecWithSSLPassword liberty "/opt/i2/utils/jks/convertKeyStore Jenny"
docker cp liberty:/opt/i2/keys/stores/i2-Jenny-keystore.p12 ${SRC_DIR}/keys/stores/

output "Adding the signed 'Imogen' user certificate to the liberty container"
runDockerExecWithSSLPassword liberty "/opt/i2/utils/jks/applyResponse Imogen"

output "Converting the 'Imogen' user key store to PKCS12 format"
runDockerExecWithSSLPassword liberty "/opt/i2/utils/jks/convertKeyStore Imogen"
docker cp liberty:/opt/i2/keys/stores/i2-Imogen-keystore.p12 ${SRC_DIR}/keys/stores/

output "Adding the signed certificate to the solr container"
docker cp ${SRC_DIR}/keys/responses/. solr:/opt/i2/keys/responses
runDockerExecWithSSLPassword solr "/opt/i2/utils/jks/applyResponse solr"

output "Adding the signed certificate to the solr2 container"
docker cp ${SRC_DIR}/keys/responses/. solr2:/opt/i2/keys/responses
runDockerExecWithSSLPassword solr2 "/opt/i2/utils/jks/applyResponse solr2"

output "Adding the signed certificate to the zookeeper container"
docker cp ${SRC_DIR}/keys/responses/. zookeeper:/opt/i2/keys/responses
runDockerExecWithSSLPassword zookeeper "/opt/i2/utils/jks/applyResponse zookeeper"

output "Adding the signed certificate to the zookeeper2 container"
docker cp ${SRC_DIR}/keys/responses/. zookeeper2:/opt/i2/keys/responses
runDockerExecWithSSLPassword zookeeper2 "/opt/i2/utils/jks/applyResponse zookeeper2"

output "Adding the signed certificate to the zookeeper3 container"
docker cp ${SRC_DIR}/keys/responses/. zookeeper3:/opt/i2/keys/responses
runDockerExecWithSSLPassword zookeeper3 "/opt/i2/utils/jks/applyResponse zookeeper3"

case "${dbDialect}" in
  "db2")
    output "Adding the signed certificate to the db2 container"
    docker cp ${SRC_DIR}/keys/responses/. db2:/opt/i2/keys/responses
    runDockerExecWithSSLPassword db2 "/opt/i2/utils/cms/applyResponse db2"
    ;;
  "sqlserver")
    output "Adding the signed certificate to the sqlserver container"
    docker cp ${SRC_DIR}/keys/responses/. sqlserver:/opt/i2/keys/responses
    ;;
  "postgres")
    output "Adding the signed certificate to the postgres container"
    docker cp ${SRC_DIR}/keys/responses/. postgres:/opt/i2/keys/responses
    ;;
esac

if [ "$(docker ps -q -f name=ihs)" ]; then
  output "Adding the signed certificate to the ihs container"
  docker cp ${SRC_DIR}/keys/responses/. ihs:/opt/i2/keys/responses
  runDockerExecWithSSLPassword ihs "/opt/i2/utils/cms/applyResponse ihs"
fi

if [ "$(docker ps -q -f name=connector)" ]; then
  output "Adding the signed certificate to the connector container"
  docker cp ${SRC_DIR}/keys/responses/. connector:/opt/i2/keys/responses
fi