#!/bin/bash
# i2, i2 Group, the i2 Group logo, and i2group.com are trademarks of N.Harris Computer Corporation.
# © N.Harris Computer Corporation (2022-2023)
#
# SPDX short identifier: MIT

#####################################################################################
#                                                                                   #
#  Script to create CA cert and key.                                                #
#                                                                                   #
#  This script is called as part of the createKeysAndStores script.                 #
#                                                                                   #
#####################################################################################

. ${UTILS_PATH}/variables
. ${UTILS_PATH}/functions

pushd ${IMAGES_PATH}/common/ca/ca/
# If CA cert or key does not exist then create new
if [[ ! -e "CA.cer"  || ! -e "CA.key" ]]; then
    echo "Creating new CA certificate"
    openssl req -new -subj "/ST=Cambridgeshire/L=Cambridge/O=i2Group/OU=i2/CN=i2CA/C=GB" -sha256 -nodes -newkey rsa:4096 -keyout CA.key -out CA.csr
    openssl x509 -req -sha256 -extfile x509.ext -extensions ca -in CA.csr -signkey CA.key -days 1095 -out CA.cer
else
    echo "Reusing existing CA certificate"
fi
popd
