#!/bin/bash
# MIT License
#
# Copyright (c) 2022, N. Harris Computer Corporation
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

#####################################################################################
#                                                                                   #
#  Script to create a certificate signing request using OpenSSL.                    #
#                                                                                   #
#####################################################################################

. /opt/IBM/utils/functions

#The value passed in when the script is called, this is the name of a container.
uri=$1

#Set the variables for the specified container name
keyFile=/opt/IBM/keys/stores/i2-${uri}-key.key
out=/opt/IBM/keys/requests/${uri}-key.csr

#Make the requests directory
mkdir -p /opt/IBM/keys/requests

#Create the stores directory
mkdir -p /opt/IBM/keys/stores

#Generate new certificate pair for the container
runCommandUntilSuccess "openssl genrsa -passout env:SSL_PASSWORD -out ${keyFile} 2048"

#Create certificate signing request for the public certificate
runCommandUntilSuccess "openssl req -new -key ${keyFile} -subj \"/C=GB/CN=${uri}.eianet\" -out ${out}"

#Change ownership to make visible to keys group
chown -R root:keys /opt/IBM/keys
chmod -R 650 /opt/IBM/keys
