#!/bin/bash
# i2, i2 Group, the i2 Group logo, and i2group.com are trademarks of N.Harris Computer Corporation.
# © N.Harris Computer Corporation (2022)
#
# SPDX short identifier: MIT

#####################################################################################
#                                                                                   #
#  Script to set up the key stores used for SSL.                                    #
#                                                                                   #
#####################################################################################
. /home/db2inst1/sqllib/db2profile

keystoreFile=/opt/i2/keys/stores/i2-db2-keystore.kdb
stashFile=/opt/i2/keys/stores/i2-db2-keystore.sth

cd /opt/i2/keys/stores
chown root:keys $keystoreFile
chmod g+r $keystoreFile
chown root:keys $stashFile
chmod g+r $stashFile
