#!/bin/bash
# i2, i2 Group, the i2 Group logo, and i2group.com are trademarks of N.Harris Computer Corporation.
# © N.Harris Computer Corporation (2022-2023)
#
# SPDX short identifier: MIT

#####################################################################################
#                                                                                   #
#  Script to add the signed certificates into their corresponding key store.        #
#                                                                                   #
#####################################################################################
. /opt/i2/utils/functions

#The value passed in when the script is called, this is the name of a container.
#If optional second parameter is passed in, the second parameter will be used as the keyStoreId.
uri=$1
keyStoreId=${2:-$1}

#Set the variables for the specified container name
utils=/opt/i2/utils
keystoreFile=/opt/i2/keys/stores/i2-${keyStoreId}-keystore.jks
keyName=${uri}key
in=/opt/i2/keys/responses/${uri}-key.cer


#Import the certificate authority certificate
runCommandUntilSuccess "/opt/i2/i2analyze/toolkit/tools/java/bin/keytool -importcert -alias ca -keystore $keystoreFile -file ${utils}/keys/CA.cer -keypass:env SSL_PASSWORD -storepass:env SSL_PASSWORD -noprompt"

#Import the signed public certificate to the store. The existing unsigned public certificate is replaced with the signed version.
runCommandUntilSuccess "/opt/i2/i2analyze/toolkit/tools/java/bin/keytool -importcert -alias $keyName -keystore $keystoreFile -file $in -keypass:env SSL_PASSWORD -storepass:env SSL_PASSWORD -noprompt"
