#!/bin/bash
# i2, i2 Group, the i2 Group logo, and i2group.com are trademarks of N.Harris Computer Corporation.
# © N.Harris Computer Corporation (2022-2023)
#
# SPDX short identifier: MIT

#####################################################################################
#                                                                                   #
#  Script to create a certificate signing request using Java keytool.               #
#                                                                                   #
#####################################################################################
. /opt/i2/utils/functions

#The value passed in when the script is called, this is the name of a container.
#If optional second parameter is passed in, the second parameter will be used as the keyStoreId.
#If optional third parameter is passed in, the third parameter will be used as the CN value.
uri=$1
keyStoreId=${2:-$1}
commonName=${3:-${1}.eianet}

#Set the variables for the specified container name
keystoreFile=/opt/i2/keys/stores/i2-${keyStoreId}-keystore.jks
keyName=${uri}key
out=/opt/i2/keys/requests/${uri}-key.csr

#Create the requests directory
mkdir -p /opt/i2/keys/requests

#Create the stores directory
mkdir -p /opt/i2/keys/stores

#Generate new certificate pair for the container, where the CN matches the host name of the container
runCommandUntilSuccess "/opt/i2/i2analyze/toolkit/tools/java/bin/keytool -genkeypair -alias $keyName -keystore $keystoreFile -dname CN=$commonName -keyalg RSA -keypass:env SSL_PASSWORD -storepass:env SSL_PASSWORD"

#Create certificate signing request for the public certificate
runCommandUntilSuccess "/opt/i2/i2analyze/toolkit/tools/java/bin/keytool -certreq -keystore $keystoreFile -alias $keyName -keyalg RSA -keysize 2048 -file $out -storepass:env SSL_PASSWORD"

#Change ownership to make visible to keys group
chown -R root:keys /opt/i2/keys
chmod -R 650 /opt/i2/keys
