#!/bin/bash
# i2, i2 Group, the i2 Group logo, and i2group.com are trademarks of N.Harris Computer Corporation.
# © N.Harris Computer Corporation (2022-2023)
#
# SPDX short identifier: MIT

#####################################################################################
#                                                                                   #
#  Script to create a trust store using Java keytool.                               #
#  One trust store is used by all of the containers, because it contains the        #
#  certificate authority signer certificate.                                        #
#                                                                                   #
#####################################################################################
. /opt/i2/utils/functions

utils=/opt/i2/utils
keystoreFile=/opt/i2/keys/stores/i2-jks-truststore.jks

#Create the stores directory
mkdir -p /opt/i2/keys/stores

#Import the certificate authority certificate into the trust store
runCommandUntilSuccess "/opt/i2/i2analyze/toolkit/tools/java/bin/keytool -importcert -alias ca -keystore $keystoreFile -file ${utils}/keys/CA.cer -keypass:env SSL_PASSWORD -storepass:env SSL_PASSWORD -noprompt"

#Change ownership of the directory for the keys group
chown -R root:keys /opt/i2/keys
chmod -R 650 /opt/i2/keys
