#!/bin/bash
# i2, i2 Group, the i2 Group logo, and i2group.com are trademarks of N.Harris Computer Corporation.
# © N.Harris Computer Corporation (2022-2023)
#
# SPDX short identifier: MIT

#####################################################################################
#                                                                                   #
#  Internal script to be called on container startup and add any necessary startup  #
#  extension                                                                        #
#                                                                                   #
#####################################################################################
