#!/bin/bash
# i2, i2 Group, the i2 Group logo, and i2group.com are trademarks of N.Harris Computer Corporation.
# © N.Harris Computer Corporation (2022-2023)
#
# SPDX short identifier: MIT

#####################################################################################
#                                                                                   #
#  Script to create a certificate signing request using OpenSSL.                    #
#                                                                                   #
#####################################################################################

. /opt/i2/utils/functions

#The value passed in when the script is called, this is the name of a container.
uri=$1

#Set the variables for the specified container name
keyFile=/opt/i2/keys/stores/i2-${uri}-key.key
out=/opt/i2/keys/requests/${uri}-key.csr

#Make the requests directory
mkdir -p /opt/i2/keys/requests

#Create the stores directory
mkdir -p /opt/i2/keys/stores

#Generate new certificate pair for the container
runCommandUntilSuccess "openssl genrsa -passout env:SSL_PASSWORD -out ${keyFile} 2048"

#Create certificate signing request for the public certificate
runCommandUntilSuccess "openssl req -new -key ${keyFile} -subj \"/C=GB/CN=${uri}.eianet\" -out ${out}"

#Change ownership to make visible to keys group
chown -R root:keys /opt/i2/keys
chmod -R 650 /opt/i2/keys
